version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  # Maintain Python dependencies
  - package-ecosystem: "pip"  # i.e. updates only in `pyproject.toml`
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      pip:
        patterns:
          - "*"
    cooldown:
      default-days: 7