# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-OpenBabel
version:      1.1.0
version_from: 
installdirs:  site
requires:
license:      gpl
license_url:  http://www.gnu.org/copyleft/gpl.html

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
