.TH "openbabel" 1 "27 Jul 2005" "Version 2.0" "Open Babel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openbabel \- a converter for molecular modeling data files

.br
 
.PP
\fBSYNOPSIS\fP.RS 4

.RE
.PP
\fBbabel\fP [-H<help-options>] [-V] [-m] [-d] [-h] [-p] [-s<SMARTS-pattern>] [-v<SMARTS-pattern>] [-f<#> -l<#>] [-c] [-x<format-options>] [-i<input-type>] <infile> [-o<output-type>] <outfile>
.PP
\fBDESCRIPTION\fP.RS 4

.RE
.PP
Open Babel is a program designed to interconvert a number of file formats currently used in molecular modeling software. 
.br

.br
 Note that OpenBabel can also be used as a library to import molecular formats in other software packages. See the OpenBabel web pages (http://openbabel.sourceforge.net) for more information.
.PP
\fBOPTIONS\fP.RS 4

.RE
.PP
If only input and ouput files are given, Open Babel will guess the file type from the filename extension. 
.br

.br
.PP
\fB-V\fP : Output version number and exit 
.br

.br
 \fB-H\fP : Output usage information 
.br

.br
 \fB-H<format-ID>\fP : Output formatting information and options for format specified
.br

.br
 \fB-Hall\fP : Output formatting information and options for all formats
.br

.br
 \fB-i\fP : Specifies input format, see below for the available formats 
.br

.br
 \fB-o\fP : Specifies output format, see below for the available formats 
.br

.br
 \fB-m\fP : Produce multiple output files, to allow:
.br
 * Splitting one input file - put each molecule into consecutively numbered output files 
.br
 * Batch conversion - convert each of multiple input files into a specified output format 
.br
 See examples below 
.br

.br
 \fB-d\fP : Delete Hydrogens 
.br

.br
 \fB-h\fP : Add Hydrogens 
.br

.br
 \fB-p\fP : Add Hydrogens appropriate for pH (use transforms in phmodel.txt) 
.br

.br
 \fB-t\fP : All input files describe a single molecule 
.br

.br
 \fB-f<#>\fP : For multiple entries input, start import at molecule # 
.br

.br
 \fB-l<#>\fP : For multiple entries input, stop import at molecule # 
.br

.br
 \fB-c\fP : Center atomic coordinates at (0,0,0) 
.br

.br
 \fB-s<SMARTS>\fP : Convert only molecules matching the SMARTS pattern specified 
.br

.br
 \fB-v<SMARTS>\fP : Convert only molecules \fBNOT\fP matching SMARTS pattern specified 
.br

.br
 \fB-z\fP : Use options used last time, written to ~/.openbabel 
.br

.br
 \fB--\fP : Read input from standard input if specified as <infile> 
.br
 Write output to standard output if specified as <outfile> 
.br

.br
.PP
\fBFILE FORMATS\fP.RS 4

.RE
.PP
The following formats are currently supported by Open Babel: 
.br
 alc -- Alchemy format 
.br
 bgf -- BGF format 
.br
 box -- Dock 3.5 Box format 
.br
 bs -- Ball and Stick format 
.br
 c3d1 -- Chem3D Cartesian 1 format 
.br
 c3d2 -- Chem3D Cartesian2 format 
.br
 caccrt -- Cacao format 
.br
 cache -- CAChe format [Writeonly] 
.br
 cacint -- CacaoInternal format [Writeonly] 
.br
 car -- MSI Biosym/Insight II CAR format [Readonly] 
.br
 ccc -- CCC format [Readonly] 
.br
 cht -- ChemTool format [Writeonly] 
.br
 cml -- Chemical Markup Language 
.br
 crk2d -- Chemical Resource Kit diagram format (2D) 
.br
 crk3d -- Chemical Resource Kit 3D format 
.br
 csr -- CSR format [Writeonly] 
.br
 cssr -- CSD CSSR format [Writeonly] 
.br
 ct -- ChemDraw Connection Table format 
.br
 dmol -- DMol3 coordinates format 
.br
 ent -- Protein Data Bank format 
.br
 feat -- Feature format 
.br
 fh -- Fenske-Hall Z-Matrix format [Writeonly] 
.br
 fix -- FIX format [Writeonly] 
.br
 g03 -- Gaussian98/03 Cartesian [Writeonly] 
.br
 g98 -- Gaussian98/03 Cartesian [Writeonly] 
.br
 gam -- GAMESS Output 
.br
 gamout -- GAMESS Output 
.br
 gau -- Gaussian98/03 Cartesian [Writeonly] 
.br
 gpr -- Ghemical format 
.br
 gr96 -- GROMOS96 format [Writeonly] 
.br
 hin -- HyperChem Input format 
.br
 ins -- ShelX format [Readonly] 
.br
 jout -- Jaguar output format 
.br
 mdl -- MDL MOL format 
.br
 mm1gp -- Ghemical format 
.br
 mm3 -- MM3 format [Writeonly] 
.br
 mmd -- MacroMod format 
.br
 mmod -- MacroMod format 
.br
 mol -- MDL MOL format 
.br
 mol2 -- Sybyl Mol2 format 
.br
 mopcrt -- MOPAC Cartesian format 
.br
 mopout -- MOPAC Output format [Readonly] 
.br
 mpqc -- MPQC format [Readonly] 
.br
 nwo -- NWChem format 
.br
 pdb -- Protein Data Bank format 
.br
 pov -- POV-Ray input format [Writeonly] 
.br
 pqs -- Parallel Quantum Solutions format 
.br
 prep -- Amber Prep format [Readonly] 
.br
 qcout -- QChem output format 
.br
 qm1gp -- Ghemical format 
.br
 report -- Report format [Writeonly] 
.br
 res -- ShelX format [Readonly] 
.br
 rxn -- MDL RXN format 
.br
 sd -- MDL MOL format 
.br
 sdf -- MDL MOL format 
.br
 smi -- SMILES format 
.br
 tmol -- TurboMole Coordinate format 
.br
 txyz -- Tinker format [Writeonly] 
.br
 unixyz -- UniChem XYZ format 
.br
 vmol -- ViewMol format 
.br
 xed -- XED format [Writeonly] 
.br
 xyz -- XYZ cartesian coordinates format 
.br
 zin -- ZINDO input format [Writeonly]
.PP
\fBFORMAT OPTIONS\fP.RS 4
Individual file formats may have additional formatting options. 
.br
 Input format options are preceded by 'a', e.g. -as 
.br
 Output format options are preceded by 'x', e.g. -xn 
.br
 For further specific information and options, use -H<format-type> 
.br
 e.g., -Hcml
.RE
.PP
\fBEXAMPLES\fP.RS 4

.IP "\(bu" 2
Standard conversion 
.br
 babel -ixyz ethanol.xyz -opdb ethanol.pdb 
.br

.IP "\(bu" 2
Conversion from a SMI file in STDIN to a Mol2 file written to STDOUT 
.br
 babel -ismi -omol2 
.br

.IP "\(bu" 2
Split a multi-molecule file into new1.smi, new2.smi, etc. 
.br
 babel infile.mol new.smi -m 
.br

.PP
.RE
.PP
\fBAUTHORS\fP.RS 4

.RE
.PP
Open Babel is derived from OElib, written by \fBMatt\fP \fBStahl\fP and other developers at Open Eye Scientific, Inc., which is a rewrite of the classic babel program. Open Babel is currently maintained by \fBGeoff\fP \fBHutchison\fP and \fBMichael\fP \fBBanck\fP.
.PP
For more contributors to Open Babel, see http://openbabel.sourceforge.net/THANKS.shtml
.PP
\fBCOPYRIGHT\fP.RS 4
Copyright (C) 1998-2001 by OpenEye Scientific Software, Inc. Some portions Copyright (C) 2001-2005 by Geoffrey R. Hutchison 
.br
 
.br
 This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2 of the License.
.br
 
.br
 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.RE
.PP
\fBSEE ALSO\fP.RS 4
The web pages for OpenBabel can be found at http://openbabel.sourceforge.net/ 
.RE
.PP

