.Dd October 10, 2019
.Dt OBABEL 1 URM
.Os "Open Babel" 3.1
.Sh NAME
.Nm obabel
.Nd "a converter for chemistry and molecular modeling data files"
.Sh SYNOPSIS
.Nm
.Fl H Ns Ar help-options
.Nm
.Op Ar OPTIONS
.Op Fl i Ns Ar input-type | Fl : Ns Ar SMILES-string
.Ar infile
.Op Fl o Ns Ar output-type
.Fl O Ns Ar outfile
.Sh DESCRIPTION
.Nm
is a cross\-platform program designed to interconvert
between many file formats used in molecular modeling and computational
chemistry and related areas.
.Pp
Open Babel is also a complete programmers toolkit for developing
chemistry software.
For more information, see the Open Babel web pages
\%<\fBhttps://openbabel.org/\fR>.
.Sh OPTIONS
If only input and output files are given, Open Babel will guess the
file type from the filename extension.
.Bl -tag -width flag
.It Fl : Ns Ar SMILES-string
Enter SMILES string and use it in place of an input file.
The
.Ar SMILES-string
might need to be enclosed in quotation marks to avoid shell interpretation.
More than one can be used, and a molecule title can be included if enclosed in
quotes.
.It Fl a Ns Ar options
Format\-specific input options.
See
.Fl H Ns Ar format-ID
for options allowed by a particular format
.It Fl -addtotitle
Append text to the current molecule title
.It Fl -addformula
Append the molecular formula after the current molecule title
.It Fl b
Convert dative bonds: e.g., [N+]([O\-])=O to N(=O)=O
.It Fl c
Center atomic coordinates at (0,0,0)
.It Fl C
Combine molecules in first file with others having the same name
.It Fl e
Continue after errors
.It Fl d
Delete Hydrogens
.It Fl --errorlevel Ar n
Filter the level of errors and warnings displayed:
       1 = critical errors only
       2 = include warnings too (default)
       3 = include informational messages too
       4 = include \(lqaudit log\(rq messages of changes to data
       5 = include debugging messages too
.It Fl f Ar #
For multiple entry input, start import with molecule # as the first entry
.It Fl F
Output the available fingerprint types
.It Fl h
Add hydrogens
.It Fl H
Output usage information
.It Fl H Ns Ar format-ID
Output formatting information and options for format specified
.It Fl Hall
Output formatting information and options for all formats
.It Fl i Ns Ar format-ID
Specifies input format, see below for the available formats
.It Fl j , -join
Join all input molecules into a single output molecule entry
.It Fl k
Translate computational chemistry modeling keywords (e.g., GAMESS and Gaussian)
.It Fl m
Produce multiple output files, to allow:
.Bl -dash -offset indent -compact
.It
Splitting one input file \(em put each molecule into consecutively
numbered output files
.It
Batch conversion \(em convert each of multiple input files into a
specified output format
.El
.It Fl l Ar #
For multiple entry input, stop import with molecule # as the last entry
.It Fl o Ns Ar format-ID
Specifies output format, see below for the available formats
.It Fl O Ns Ar outfile
Specify the output file
.It Fl p
Add Hydrogens appropriate for pH (use transforms in phmodel.txt)
.It Fl -property
Add or replace a property (e.g., in an MDL SD file)
.It Fl s Ar SMARTS
Convert only molecules matching the SMARTS pattern specified
.It Fl -separate
Separate disconnected fragments into individual molecular records
.It Fl t
All input files describe a single molecule
.It Fl -title Ar title
Add or replace molecular title
.It Fl x Ns Ar options
Format\-specific output options.
See
.Fl H Ar format-ID
for options allowed by a particular format
.It Fl v Ar SMARTS
Convert only molecules \fBNOT\fP matching SMARTS pattern specified
.It Fl V
Output version number and exit
.It Fl z
Compress the output with gzip
.El
.Sh "FILE FORMATS"
The following formats are currently supported by Open Babel:
.Bl -item -offset indent -compact
.It
abinit \(em ABINIT Output Format [Read\-only]
.It
acesin \(em ACES input format [Write\-only]
.It
acesout \(em ACES output format [Read\-only]
.It
acr \(em ACR format [Read\-only]
.It
adf \(em ADF cartesian input format [Write\-only]
.It
adfband \(em ADF Band output format [Read\-only]
.It
adfdftb \(em ADF DFTB output format [Read\-only]
.It
adfout \(em ADF output format [Read\-only]
.It
alc \(em Alchemy format
.It
aoforce \(em Turbomole AOFORCE output format [Read\-only]
.It
arc \(em Accelrys/MSI Biosym/Insight II CAR format [Read\-only]
.It
ascii \(em ASCII format [Write\-only]
.It
axsf \(em XCrySDen Structure Format [Read\-only]
.It
bgf \(em MSI BGF format
.It
box \(em Dock 3.5 Box format
.It
bs \(em Ball and Stick format
.It
c09out \(em Crystal 09 output format [Read\-only]
.It
c3d1 \(em Chem3D Cartesian 1 format
.It
c3d2 \(em Chem3D Cartesian 2 format
.It
cac \(em CAChe MolStruct format [Write\-only]
.It
caccrt \(em Cacao Cartesian format
.It
cache \(em CAChe MolStruct format [Write\-only]
.It
cacint \(em Cacao Internal format [Write\-only]
.It
can \(em Canonical SMILES format
.It
car \(em Accelrys/MSI Biosym/Insight II CAR format [Read\-only]
.It
castep \(em CASTEP format [Read\-only]
.It
ccc \(em CCC format [Read\-only]
.It
cdjson \(em ChemDoodle JSON
.It
cdx \(em ChemDraw binary format [Read\-only]
.It
cdxml \(em ChemDraw CDXML format
.It
cht \(em Chemtool format [Write\-only]
.It
cif \(em Crystallographic Information File
.It
cjson \(em Chemical JSON
.It
ck \(em ChemKin format
.It
cml \(em Chemical Markup Language
.It
cmlr \(em CML Reaction format
.It
cof \(em Culgi object file format
.It
com \(em Gaussian Input [Write\-only]
.It
confabreport \(em Confab report format [Write\-only]
.It
CONFIG \(em DL\-POLY CONFIG
.It
CONTCAR \(em VASP format
.It
CONTFF \(em MDFF format
.It
copy \(em Copy raw text [Write\-only]
.It
crk2d \(em Chemical Resource Kit diagram(2D)
.It
crk3d \(em Chemical Resource Kit 3D format
.It
csr \(em Accelrys/MSI Quanta CSR format [Write\-only]
.It
cssr \(em CSD CSSR format [Write\-only]
.It
ct \(em ChemDraw Connection Table format
.It
cub \(em Gaussian cube format
.It
cube \(em Gaussian cube format
.It
dallog \(em DALTON output format [Read\-only]
.It
dalmol \(em DALTON input format
.It
dat \(em Generic Output file format [Read\-only]
.It
dmol \(em DMol3 coordinates format
.It
dx \(em OpenDX cube format for APBS
.It
ent \(em Protein Data Bank format
.It
exyz \(em Extended XYZ cartesian coordinates format
.It
fa \(em FASTA format
.It
fasta \(em FASTA format
.It
fch \(em Gaussian formatted checkpoint file format [Read\-only]
.It
fchk \(em Gaussian formatted checkpoint file format [Read\-only]
.It
fck \(em Gaussian formatted checkpoint file format [Read\-only]
.It
feat \(em Feature format
.It
fh \(em Fenske\-Hall Z\-Matrix format [Write\-only]
.It
fhiaims \(em FHIaims XYZ format
.It
fix \(em SMILES FIX format [Write\-only]
.It
fps \(em FPS text fingerprint format (Dalke) [Write\-only]
.It
fpt \(em Fingerprint format [Write\-only]
.It
fract \(em Free Form Fractional format
.It
fs \(em Fastsearch format
.It
fsa \(em FASTA format
.It
g03 \(em Gaussian Output [Read\-only]
.It
g09 \(em Gaussian Output [Read\-only]
.It
g16 \(em Gaussian Output [Read\-only]
.It
g92 \(em Gaussian Output [Read\-only]
.It
g94 \(em Gaussian Output [Read\-only]
.It
g98 \(em Gaussian Output [Read\-only]
.It
gal \(em Gaussian Output [Read\-only]
.It
gam \(em GAMESS Output [Read\-only]
.It
gamess \(em GAMESS Output [Read\-only]
.It
gamin \(em GAMESS Input
.It
gamout \(em GAMESS Output [Read\-only]
.It
gau \(em Gaussian Input [Write\-only]
.It
gjc \(em Gaussian Input [Write\-only]
.It
gjf \(em Gaussian Input [Write\-only]
.It
got \(em GULP format [Read\-only]
.It
gpr \(em Ghemical format
.It
gr96 \(em GROMOS96 format [Write\-only]
.It
gro \(em GRO format
.It
gukin \(em GAMESS\-UK Input
.It
gukout \(em GAMESS\-UK Output
.It
gzmat \(em Gaussian Z\-Matrix Input
.It
hin \(em HyperChem HIN format
.It
HISTORY \(em DL\-POLY HISTORY [Read\-only]
.It
inchi \(em InChI format
.It
inchikey \(em InChIKey [Write\-only]
.It
inp \(em GAMESS Input
.It
ins \(em ShelX format [Read\-only]
.It
jin \(em Jaguar input format
.It
jout \(em Jaguar output format [Read\-only]
.It
k \(em Compare molecules using InChI [Write\-only]
.It
lmpdat \(em The LAMMPS data format [Write\-only]
.It
log \(em Generic Output file format [Read\-only]
.It
lpmd \(em LPMD format
.It
mae \(em Maestro format
.It
maegz \(em Maestro format
.It
mcdl \(em MCDL format
.It
mcif \(em Macromolecular Crystallographic Info
.It
MDFF \(em MDFF format
.It
mdl \(em MDL MOL format
.It
ml2 \(em Sybyl Mol2 format
.It
mmcif \(em Macromolecular Crystallographic Info
.It
mmd \(em MacroModel format
.It
mmod \(em MacroModel format
.It
mna \(em Multilevel Neighborhoods of Atoms (MNA) [Write\-only]
.It
mol \(em MDL MOL format
.It
mol2 \(em Sybyl Mol2 format
.It
mold \(em Molden format
.It
molden \(em Molden format
.It
molf \(em Molden format
.It
molreport \(em Open Babel molecule report [Write\-only]
.It
moo \(em MOPAC Output format [Read\-only]
.It
mop \(em MOPAC Cartesian format
.It
mopcrt \(em MOPAC Cartesian format
.It
mopin \(em MOPAC Internal
.It
mopout \(em MOPAC Output format [Read\-only]
.It
mp \(em Molpro input format [Write\-only]
.It
mpc \(em MOPAC Cartesian format
.It
mpd \(em MolPrint2D format [Write\-only]
.It
mpo \(em Molpro output format [Read\-only]
.It
mpqc \(em MPQC output format [Read\-only]
.It
mpqcin \(em MPQC simplified input format [Write\-only]
.It
mrv \(em Chemical Markup Language
.It
msi \(em Accelrys/MSI Cerius II MSI format [Read\-only]
.It
msms \(em M.F. Sanner\(aqs MSMS input format [Write\-only]
.It
nul \(em Outputs nothing [Write\-only]
.It
nw \(em NWChem input format [Write\-only]
.It
nwo \(em NWChem output format [Read\-only]
.It
orca \(em ORCA output format [Read\-only]
.It
orcainp \(em ORCA input format [Write\-only]
.It
out \(em Generic Output file format [Read\-only]
.It
outmol \(em DMol3 coordinates format
.It
output \(em Generic Output file format [Read\-only]
.It
paint \(em Painter format [Write\-only]
.It
pc \(em PubChem format [Read\-only]
.It
pcjson \(em PubChem JSON
.It
pcm \(em PCModel Format
.It
pdb \(em Protein Data Bank format
.It
pdbqt \(em AutoDock PDBQT format
.It
png \(em PNG 2D depiction
.It
pointcloud \(em Point cloud on VDW surface [Write\-only]
.It
pos \(em POS cartesian coordinates format [Read\-only]
.It
POSCAR \(em VASP format
.It
POSFF \(em MDFF format
.It
pov \(em POV\-Ray input format [Write\-only]
.It
pqr \(em PQR format
.It
pqs \(em Parallel Quantum Solutions format
.It
prep \(em Amber Prep format [Read\-only]
.It
pwscf \(em PWscf format [Read\-only]
.It
qcin \(em Q\-Chem input format [Write\-only]
.It
qcout \(em Q\-Chem output format [Read\-only]
.It
report \(em Open Babel report format [Write\-only]
.It
res \(em ShelX format [Read\-only]
.It
rinchi \(em RInChI [Write\-only]
.It
rsmi \(em Reaction SMILES format
.It
rxn \(em MDL RXN format
.It
sd \(em MDL MOL format
.It
sdf \(em MDL MOL format
.It
siesta \(em SIESTA format [Read\-only]
.It
smi \(em SMILES format
.It
smiles \(em SMILES format
.It
smy \(em SMILES format using Smiley parser [Read\-only]
.It
stl \(em STL 3D\-printing format [Write\-only]
.It
svg \(em SVG 2D depiction [Write\-only]
.It
sy2 \(em Sybyl Mol2 format
.It
t41 \(em ADF TAPE41 format [Read\-only]
.It
tdd \(em Thermo format
.It
text \(em Read and write raw text
.It
therm \(em Thermo format
.It
tmol \(em TurboMole Coordinate format
.It
txt \(em Title format
.It
txyz \(em Tinker XYZ format
.It
unixyz \(em UniChem XYZ format
.It
VASP \(em VASP format
.It
vmol \(em ViewMol format
.It
wln \(em Wiswesser Line Notation [Read\-only]
.It
xed \(em XED format [Write\-only]
.It
xml \(em General XML format [Read\-only]
.It
xsf \(em XCrySDen Structure Format [Read\-only]
.It
xyz \(em XYZ cartesian coordinates format
.It
yob \(em YASARA.org YOB format
.It
zin \(em ZINDO input format [Write\-only]
.El
.Sh "FORMAT OPTIONS"
Individual file formats may have additional formatting options.
.Pp
Input format options are preceded by
.Fl a ,
e.g.,
.Fl as
.Pp
Output format options are preceded by
.Fl x ,
e.g.,
.Fl xn
.Pp
For further specific information and options, use
.Fl H Ns Ar format-type ,
e.g.,
.Fl Hcml
.Sh EXAMPLES
Standard conversion:
.Dl "obabel ethanol.xyz \-Oethanol.pdb"
Conversion from a SMI file in STDIN to a Mol2 file written to STDOUT:
.Dl "obabel \-ismi \-omol2"
Split a multi\-molecule file into new1.smi, new2.smi, etc.:
.Dl "obabel infile.mol -Onew.smi \-m"
.Sh "SEE ALSO"
.Xr obenergy 1 ,
.Xr obfit 1 ,
.Xr obgrep 1 ,
.Xr obminimize 1 ,
.Xr obprop 1 ,
.Xr obrotamer 1 ,
.Xr obrotate 1 .
The web pages for Open Babel can be found at:
\%<\fBhttp://openbabel.org/\fR>
.Sh AUTHORS
.An -nosplit
A cast of many, including the current maintainers
.An Geoff Hutchison ,
.An Chris Morley ,
.An Michael Banck ,
and innumerable others who have contributed fixes and additions.
For more contributors to Open Babel, see
\%<\fBhttp://openbabel.org/wiki/THANKS\fR>
.Sh COPYRIGHT
Copyright (C) 1998\-2001 by OpenEye Scientific Software, Inc.
.br
Some portions Copyright (C) 2001\-2007 by Geoffrey R. Hutchison
.Pp
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.
.Pp
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
