.TH "obfit" 1 "5 Sep 2005" "Version 2.0" "Open Babel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obfit \- superimpose two molecules based on a pattern

.br
 
.PP
\fBSYNOPSIS\fP.RS 4

.RE
.PP
\fBobfit\fP <SMARTS-pattern> <fixed-file> <outfile>
.PP
\fBDESCRIPTION\fP.RS 4

.RE
.PP
Superimpose two molecules using a quaternion fit. The atoms used to fit the two molecules are defined by the SMARTS pattern given by the user. It is useful to align congeneric series of molecules on a common structural scaffold for 3D-QSAR studies. It can also be useful for displaying the results of conformational generation. 
.br

.br
 Any molecules matching the supplied SMARTS pattern will be rotated and translated to provide the smallest possible RMSD between the matching regions. If a molecule does not match the SMARTS pattern, it will be output with no transformation.
.PP
\fBEXAMPLES\fP.RS 4

.IP "\(bu" 2
Align all the molecules in 'moving.sdf' on a single molecule of 'fixed.sdf' by superimposing them on its N-methylpiperidyl portion 
.br
 obfit '[nh]1c2c(=O)n(C)c(=O)n(C)c2cc1' testref.sdf testmv.sdf
.PP
.RE
.PP
\fBAUTHORS\fP.RS 4

.RE
.PP
The obfit program was contributed by \fBFabien\fP \fBFontaine\fP.
.PP
Open Babel is currently maintained by \fBGeoff\fP \fBHutchison\fP, \fBChris\fP \fBMorley\fP and \fBMichael\fP \fBBanck\fP.
.PP
For more contributors to Open Babel, see http://openbabel.sourceforge.net/THANKS.shtml
.PP
\fBCOPYRIGHT\fP.RS 4
Copyright (C) 1998-2001 by OpenEye Scientific Software, Inc. Some portions Copyright (C) 2001-2005 by Geoffrey R. Hutchison 
.br
 
.br
 This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2 of the License.
.br
 
.br
 This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.RE
.PP
\fBSEE ALSO\fP.RS 4
The web pages for Open Babel can be found at http://openbabel.sourceforge.net/ 
.br
 A guide for constructing SMARTS patterns can be found at http://www.daylight.com/dayhtml/doc/theory/theory.smarts.html 
.RE
.PP

