.Dd Oct 10, 2019
.Os "Open Babel" 3.1
.Dt obsym 1 URM
.Sh NAME
.Nm obsym
.Nd "detect 3D point group symmetry"
.Sh SYNOPSIS
.Nm
.Ar filename
.Sh DESCRIPTION
Detects 3D point group symmetry and writes out symmetrized coordinates.
.Sh EXAMPLES
.Dl "obsym molecule1.cif > molecule2.cif"
.Pp
Symmetrizes coordinates of molecule1.cif and write it to molecule2.cif
.Sh SEE ALSO
.Xr obgen 1 .
.Pp
The web pages for Open Babel can be found at:
\%<\fBhttp://openbabel.org/\fR>
.Sh AUTHORS
.An -nosplit
Open Babel is developed by a cast of many, including currrent maintainers
.An Geoff Hutchison ,
.An Chris Morley ,
.An Michael Banck ,
and innumerable others who have contributed fixes and additions.
For more contributors to Open Babel, see
\%<\fBhttp://openbabel.org/wiki/THANKS\fR>
.Sh COPYRIGHT
Copyright (C) 1998-2001 by OpenEye Scientific Software, Inc.
.br
Some portions Copyright (C) 2001-2007 by Geoffrey R. Hutchison and
other contributors.
.Pp
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.
.Pp
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
