.Dd Oct 10, 2019
.Os "Open Babel" 3.0
.Dt obthermo 1 URM
.Sh NAME
.Nm obthermo
.Nd "extract the thermochemistry for a molecule"
.Sh SYNOPSIS
.Nm
.Op options
.Ar filename
.Sh DESCRIPTION
The obthermo tool can be used to extract the thermochemistry, e.g. enthalpy and
Gibbs energy of formation, and the standard entropy from e.g. a Gaussian calculation.
.Sh OPTIONS
.Bl -tag -width flag
.It Fl -symm Ar N
override symmetry number used in input file
.It Fl -nrot Ar N
number of rotatable bonds for conformational entropy
.It Fl -dbdt Ar x
temperature derivative of second virial coefficient for cp calculation
.It Fl -kj
output kJ/mol related units (default kcal/mol)
.El
.Sh SEE ALSO
.Xr obabel 1 .
.Pp
The web pages for Open Babel can be found at:
\%<\fBhttp://openbabel.org/\fR>
.Sh AUTHORS
.An -nosplit
Open Babel is developed by a cast of many, including currrent maintainers
.An Geoff Hutchison ,
.An Chris Morley ,
.An Michael Banck ,
and innumerable others who have contributed fixes and additions.
For more contributors to Open Babel, see
\%<\fBhttp://openbabel.org/wiki/THANKS\fR>
.Sh COPYRIGHT
Copyright (C) 1998-2001 by OpenEye Scientific Software, Inc.
.br
Some portions Copyright (C) 2001-2008 by Geoffrey R. Hutchison and
other contributors.
.Pp
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.
.Pp
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.
