/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class DataOrigin {
  public final static DataOrigin any = new DataOrigin("any");
  public final static DataOrigin fileformatInput = new DataOrigin("fileformatInput");
  public final static DataOrigin userInput = new DataOrigin("userInput");
  public final static DataOrigin perceived = new DataOrigin("perceived");
  public final static DataOrigin external = new DataOrigin("external");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DataOrigin swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DataOrigin.class + " with value " + swigValue);
  }

  private DataOrigin(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DataOrigin(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DataOrigin(String swigName, DataOrigin swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DataOrigin[] swigValues = { any, fileformatInput, userInput, perceived, external };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

