/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBIsotopeTable extends OBGlobalDataBase {
  private long swigCPtr;

  protected OBIsotopeTable(long cPtr, boolean cMemoryOwn) {
    super(openbabelJNI.SWIGOBIsotopeTableUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBIsotopeTable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBIsotopeTable(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OBIsotopeTable() {
    this(openbabelJNI.new_OBIsotopeTable(), true);
  }

  public long GetSize() {
    return openbabelJNI.OBIsotopeTable_GetSize(swigCPtr, this);
  }

  public void ParseLine(String arg0) {
    openbabelJNI.OBIsotopeTable_ParseLine(swigCPtr, this, arg0);
  }

  public double GetExactMass(long atomicNum, long isotope) {
    return openbabelJNI.OBIsotopeTable_GetExactMass__SWIG_0(swigCPtr, this, atomicNum, isotope);
  }

  public double GetExactMass(long atomicNum) {
    return openbabelJNI.OBIsotopeTable_GetExactMass__SWIG_1(swigCPtr, this, atomicNum);
  }

}
