/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_a_4__char {
  private long swigCPtr;

  protected SWIGTYPE_p_a_4__char(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_a_4__char() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_a_4__char obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

