/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class DataSource {
  public final static DataSource any = new DataSource("any");
  public final static DataSource readInput = new DataSource("readInput");
  public final static DataSource userInput = new DataSource("userInput");
  public final static DataSource perceived = new DataSource("perceived");
  public final static DataSource external = new DataSource("external");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DataSource swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DataSource.class + " with value " + swigValue);
  }

  private DataSource(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DataSource(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DataSource(String swigName, DataSource swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DataSource[] swigValues = { any, readInput, userInput, perceived, external };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

