/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DoubleType {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DoubleType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_DoubleType(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setHi(long value) {
    net.sourceforge.openbabelJNI.DoubleType_hi_set(swigCPtr, this, value);
  }

  public long getHi() {
    return net.sourceforge.openbabelJNI.DoubleType_hi_get(swigCPtr, this);
  }

  public void setLo(long value) {
    net.sourceforge.openbabelJNI.DoubleType_lo_set(swigCPtr, this, value);
  }

  public long getLo() {
    return net.sourceforge.openbabelJNI.DoubleType_lo_get(swigCPtr, this);
  }

  public DoubleType() {
    this(net.sourceforge.openbabelJNI.new_DoubleType(), true);
  }

}
