/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface net.sourceforge.openbabelConstants {
  public final static String FILE_SEP_CHAR = net.sourceforge.openbabelJNI.FILE_SEP_CHAR_get();
  public final static double PI = net.sourceforge.openbabelJNI.PI_get();
  public final static double RAD_TO_DEG = net.sourceforge.openbabelJNI.RAD_TO_DEG_get();
  public final static double DEG_TO_RAD = net.sourceforge.openbabelJNI.DEG_TO_RAD_get();
  public final static int NOTREADABLE = net.sourceforge.openbabelJNI.NOTREADABLE_get();
  public final static int READONEONLY = net.sourceforge.openbabelJNI.READONEONLY_get();
  public final static int READBINARY = net.sourceforge.openbabelJNI.READBINARY_get();
  public final static int ZEROATOMSOK = net.sourceforge.openbabelJNI.ZEROATOMSOK_get();
  public final static int NOTWRITABLE = net.sourceforge.openbabelJNI.NOTWRITABLE_get();
  public final static int WRITEONEONLY = net.sourceforge.openbabelJNI.WRITEONEONLY_get();
  public final static int WRITEBINARY = net.sourceforge.openbabelJNI.WRITEBINARY_get();
  public final static int DEFAULTFORMAT = net.sourceforge.openbabelJNI.DEFAULTFORMAT_get();
  public final static int MAXSETNO = net.sourceforge.openbabelJNI.MAXSETNO_get();
  public final static int MAXELEM = net.sourceforge.openbabelJNI.MAXELEM_get();
  public final static int MINELEM = net.sourceforge.openbabelJNI.MINELEM_get();
  public final static int MAXRES = net.sourceforge.openbabelJNI.MAXRES_get();
  public final static int MINRES = net.sourceforge.openbabelJNI.MINRES_get();
  public final static int AA_ALA = net.sourceforge.openbabelJNI.AA_ALA_get();
  public final static int AA_GLY = net.sourceforge.openbabelJNI.AA_GLY_get();
  public final static int AA_LEU = net.sourceforge.openbabelJNI.AA_LEU_get();
  public final static int AA_SER = net.sourceforge.openbabelJNI.AA_SER_get();
  public final static int AA_VAL = net.sourceforge.openbabelJNI.AA_VAL_get();
  public final static int AA_THR = net.sourceforge.openbabelJNI.AA_THR_get();
  public final static int AA_LYS = net.sourceforge.openbabelJNI.AA_LYS_get();
  public final static int AA_ASP = net.sourceforge.openbabelJNI.AA_ASP_get();
  public final static int AA_ILE = net.sourceforge.openbabelJNI.AA_ILE_get();
  public final static int AA_ASN = net.sourceforge.openbabelJNI.AA_ASN_get();
  public final static int AA_GLU = net.sourceforge.openbabelJNI.AA_GLU_get();
  public final static int AA_PRO = net.sourceforge.openbabelJNI.AA_PRO_get();
  public final static int AA_ARG = net.sourceforge.openbabelJNI.AA_ARG_get();
  public final static int AA_PHE = net.sourceforge.openbabelJNI.AA_PHE_get();
  public final static int AA_GLN = net.sourceforge.openbabelJNI.AA_GLN_get();
  public final static int AA_TYR = net.sourceforge.openbabelJNI.AA_TYR_get();
  public final static int AA_HIS = net.sourceforge.openbabelJNI.AA_HIS_get();
  public final static int AA_CYS = net.sourceforge.openbabelJNI.AA_CYS_get();
  public final static int AA_MET = net.sourceforge.openbabelJNI.AA_MET_get();
  public final static int AA_TRP = net.sourceforge.openbabelJNI.AA_TRP_get();
  public final static int OB_4RING_ATOM = net.sourceforge.openbabelJNI.OB_4RING_ATOM_get();
  public final static int OB_3RING_ATOM = net.sourceforge.openbabelJNI.OB_3RING_ATOM_get();
  public final static int OB_AROMATIC_ATOM = net.sourceforge.openbabelJNI.OB_AROMATIC_ATOM_get();
  public final static int OB_RING_ATOM = net.sourceforge.openbabelJNI.OB_RING_ATOM_get();
  public final static int OB_CSTEREO_ATOM = net.sourceforge.openbabelJNI.OB_CSTEREO_ATOM_get();
  public final static int OB_ACSTEREO_ATOM = net.sourceforge.openbabelJNI.OB_ACSTEREO_ATOM_get();
  public final static int OB_DONOR_ATOM = net.sourceforge.openbabelJNI.OB_DONOR_ATOM_get();
  public final static int OB_ACCEPTOR_ATOM = net.sourceforge.openbabelJNI.OB_ACCEPTOR_ATOM_get();
  public final static int OB_CHIRAL_ATOM = net.sourceforge.openbabelJNI.OB_CHIRAL_ATOM_get();
  public final static int OB_POS_CHIRAL_ATOM = net.sourceforge.openbabelJNI.OB_POS_CHIRAL_ATOM_get();
  public final static int OB_NEG_CHIRAL_ATOM = net.sourceforge.openbabelJNI.OB_NEG_CHIRAL_ATOM_get();
  public final static int OB_ATOM_HAS_NO_H = net.sourceforge.openbabelJNI.OB_ATOM_HAS_NO_H_get();
  public final static int OB_AROMATIC_BOND = net.sourceforge.openbabelJNI.OB_AROMATIC_BOND_get();
  public final static int OB_WEDGE_BOND = net.sourceforge.openbabelJNI.OB_WEDGE_BOND_get();
  public final static int OB_HASH_BOND = net.sourceforge.openbabelJNI.OB_HASH_BOND_get();
  public final static int OB_RING_BOND = net.sourceforge.openbabelJNI.OB_RING_BOND_get();
  public final static int OB_TORUP_BOND = net.sourceforge.openbabelJNI.OB_TORUP_BOND_get();
  public final static int OB_TORDOWN_BOND = net.sourceforge.openbabelJNI.OB_TORDOWN_BOND_get();
  public final static int OB_KSINGLE_BOND = net.sourceforge.openbabelJNI.OB_KSINGLE_BOND_get();
  public final static int OB_KDOUBLE_BOND = net.sourceforge.openbabelJNI.OB_KDOUBLE_BOND_get();
  public final static int OB_KTRIPLE_BOND = net.sourceforge.openbabelJNI.OB_KTRIPLE_BOND_get();
  public final static int OB_CLOSURE_BOND = net.sourceforge.openbabelJNI.OB_CLOSURE_BOND_get();
  public final static int OB_SSSR_MOL = net.sourceforge.openbabelJNI.OB_SSSR_MOL_get();
  public final static int OB_RINGFLAGS_MOL = net.sourceforge.openbabelJNI.OB_RINGFLAGS_MOL_get();
  public final static int OB_AROMATIC_MOL = net.sourceforge.openbabelJNI.OB_AROMATIC_MOL_get();
  public final static int OB_ATOMTYPES_MOL = net.sourceforge.openbabelJNI.OB_ATOMTYPES_MOL_get();
  public final static int OB_CHIRALITY_MOL = net.sourceforge.openbabelJNI.OB_CHIRALITY_MOL_get();
  public final static int OB_PCHARGE_MOL = net.sourceforge.openbabelJNI.OB_PCHARGE_MOL_get();
  public final static int OB_HYBRID_MOL = net.sourceforge.openbabelJNI.OB_HYBRID_MOL_get();
  public final static int OB_IMPVAL_MOL = net.sourceforge.openbabelJNI.OB_IMPVAL_MOL_get();
  public final static int OB_KEKULE_MOL = net.sourceforge.openbabelJNI.OB_KEKULE_MOL_get();
  public final static int OB_CLOSURE_MOL = net.sourceforge.openbabelJNI.OB_CLOSURE_MOL_get();
  public final static int OB_H_ADDED_MOL = net.sourceforge.openbabelJNI.OB_H_ADDED_MOL_get();
  public final static int OB_PH_CORRECTED_MOL = net.sourceforge.openbabelJNI.OB_PH_CORRECTED_MOL_get();
  public final static int OB_AROM_CORRECTED_MOL = net.sourceforge.openbabelJNI.OB_AROM_CORRECTED_MOL_get();
  public final static int OB_CHAINS_MOL = net.sourceforge.openbabelJNI.OB_CHAINS_MOL_get();
  public final static int OB_TCHARGE_MOL = net.sourceforge.openbabelJNI.OB_TCHARGE_MOL_get();
  public final static int OB_TSPIN_MOL = net.sourceforge.openbabelJNI.OB_TSPIN_MOL_get();
  public final static int OB_CURRENT_CONFORMER = net.sourceforge.openbabelJNI.OB_CURRENT_CONFORMER_get();
  public final static int BUFF_SIZE = net.sourceforge.openbabelJNI.BUFF_SIZE_get();
}
