/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBAtomBondIter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBAtomBondIter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBAtomBondIter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBAtomBondIter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBAtomBondIter() {
    this(openbabelJNI.new_OBAtomBondIter__SWIG_0(), true);
  }

  public OBAtomBondIter(OBAtom atm) {
    this(openbabelJNI.new_OBAtomBondIter__SWIG_1(OBAtom.getCPtr(atm), atm), true);
  }

  public OBAtomBondIter(OBAtomBondIter bi) {
    this(openbabelJNI.new_OBAtomBondIter__SWIG_2(OBAtomBondIter.getCPtr(bi), bi), true);
  }

  public OBBond __deref__() {
    long cPtr = openbabelJNI.OBAtomBondIter___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new OBBond(cPtr, false);
  }

  public OBBond __ref__() {
    return new OBBond(openbabelJNI.OBAtomBondIter___ref__(swigCPtr, this), false);
  }

  public void setVisit(boolean value) {
    openbabelJNI.OBAtomBondIter_Visit_set(swigCPtr, this, value);
  }

  public boolean getVisit() {
    return openbabelJNI.OBAtomBondIter_Visit_get(swigCPtr, this);
  }

  public void SetIdx(int idx) {
    openbabelJNI.OBAtomBondIter_SetIdx(swigCPtr, this, idx);
  }

  public void SetBO(int order) {
    openbabelJNI.OBAtomBondIter_SetBO(swigCPtr, this, order);
  }

  public void SetBondOrder(int order) {
    openbabelJNI.OBAtomBondIter_SetBondOrder(swigCPtr, this, order);
  }

  public void SetBegin(OBAtom begin) {
    openbabelJNI.OBAtomBondIter_SetBegin(swigCPtr, this, OBAtom.getCPtr(begin), begin);
  }

  public void SetEnd(OBAtom end) {
    openbabelJNI.OBAtomBondIter_SetEnd(swigCPtr, this, OBAtom.getCPtr(end), end);
  }

  public void SetParent(OBMol ptr) {
    openbabelJNI.OBAtomBondIter_SetParent(swigCPtr, this, OBMol.getCPtr(ptr), ptr);
  }

  public void SetLength(OBAtom fixed, double length) {
    openbabelJNI.OBAtomBondIter_SetLength(swigCPtr, this, OBAtom.getCPtr(fixed), fixed, length);
  }

  public void Set(int index, OBAtom begin, OBAtom end, int order, int flags) {
    openbabelJNI.OBAtomBondIter_Set(swigCPtr, this, index, OBAtom.getCPtr(begin), begin, OBAtom.getCPtr(end), end, order, flags);
  }

  public void SetKSingle() {
    openbabelJNI.OBAtomBondIter_SetKSingle(swigCPtr, this);
  }

  public void SetKDouble() {
    openbabelJNI.OBAtomBondIter_SetKDouble(swigCPtr, this);
  }

  public void SetKTriple() {
    openbabelJNI.OBAtomBondIter_SetKTriple(swigCPtr, this);
  }

  public void SetAromatic() {
    openbabelJNI.OBAtomBondIter_SetAromatic(swigCPtr, this);
  }

  public void SetHash() {
    openbabelJNI.OBAtomBondIter_SetHash(swigCPtr, this);
  }

  public void SetWedge() {
    openbabelJNI.OBAtomBondIter_SetWedge(swigCPtr, this);
  }

  public void SetUp() {
    openbabelJNI.OBAtomBondIter_SetUp(swigCPtr, this);
  }

  public void SetDown() {
    openbabelJNI.OBAtomBondIter_SetDown(swigCPtr, this);
  }

  public void SetInRing() {
    openbabelJNI.OBAtomBondIter_SetInRing(swigCPtr, this);
  }

  public void SetClosure() {
    openbabelJNI.OBAtomBondIter_SetClosure(swigCPtr, this);
  }

  public void UnsetHash() {
    openbabelJNI.OBAtomBondIter_UnsetHash(swigCPtr, this);
  }

  public void UnsetWedge() {
    openbabelJNI.OBAtomBondIter_UnsetWedge(swigCPtr, this);
  }

  public void UnsetUp() {
    openbabelJNI.OBAtomBondIter_UnsetUp(swigCPtr, this);
  }

  public void UnsetDown() {
    openbabelJNI.OBAtomBondIter_UnsetDown(swigCPtr, this);
  }

  public void UnsetAromatic() {
    openbabelJNI.OBAtomBondIter_UnsetAromatic(swigCPtr, this);
  }

  public void UnsetKekule() {
    openbabelJNI.OBAtomBondIter_UnsetKekule(swigCPtr, this);
  }

  public long GetIdx() {
    return openbabelJNI.OBAtomBondIter_GetIdx(swigCPtr, this);
  }

  public long GetBO() {
    return openbabelJNI.OBAtomBondIter_GetBO(swigCPtr, this);
  }

  public long GetBondOrder() {
    return openbabelJNI.OBAtomBondIter_GetBondOrder(swigCPtr, this);
  }

  public long GetFlags() {
    return openbabelJNI.OBAtomBondIter_GetFlags(swigCPtr, this);
  }

  public long GetBeginAtomIdx() {
    return openbabelJNI.OBAtomBondIter_GetBeginAtomIdx(swigCPtr, this);
  }

  public long GetEndAtomIdx() {
    return openbabelJNI.OBAtomBondIter_GetEndAtomIdx(swigCPtr, this);
  }

  public OBAtom GetBeginAtom() {
    long cPtr = openbabelJNI.OBAtomBondIter_GetBeginAtom__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBAtom GetEndAtom() {
    long cPtr = openbabelJNI.OBAtomBondIter_GetEndAtom__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBAtom GetNbrAtom(OBAtom ptr) {
    long cPtr = openbabelJNI.OBAtomBondIter_GetNbrAtom(swigCPtr, this, OBAtom.getCPtr(ptr), ptr);
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBMol GetParent() {
    long cPtr = openbabelJNI.OBAtomBondIter_GetParent(swigCPtr, this);
    return (cPtr == 0) ? null : new OBMol(cPtr, false);
  }

  public double GetEquibLength() {
    return openbabelJNI.OBAtomBondIter_GetEquibLength(swigCPtr, this);
  }

  public double GetLength() {
    return openbabelJNI.OBAtomBondIter_GetLength(swigCPtr, this);
  }

  public long GetNbrAtomIdx(OBAtom ptr) {
    return openbabelJNI.OBAtomBondIter_GetNbrAtomIdx(swigCPtr, this, OBAtom.getCPtr(ptr), ptr);
  }

  public boolean IsAromatic() {
    return openbabelJNI.OBAtomBondIter_IsAromatic(swigCPtr, this);
  }

  public boolean IsInRing() {
    return openbabelJNI.OBAtomBondIter_IsInRing(swigCPtr, this);
  }

  public boolean IsRotor() {
    return openbabelJNI.OBAtomBondIter_IsRotor(swigCPtr, this);
  }

  public boolean IsAmide() {
    return openbabelJNI.OBAtomBondIter_IsAmide(swigCPtr, this);
  }

  public boolean IsPrimaryAmide() {
    return openbabelJNI.OBAtomBondIter_IsPrimaryAmide(swigCPtr, this);
  }

  public boolean IsSecondaryAmide() {
    return openbabelJNI.OBAtomBondIter_IsSecondaryAmide(swigCPtr, this);
  }

  public boolean IsEster() {
    return openbabelJNI.OBAtomBondIter_IsEster(swigCPtr, this);
  }

  public boolean IsCarbonyl() {
    return openbabelJNI.OBAtomBondIter_IsCarbonyl(swigCPtr, this);
  }

  public boolean IsSingle() {
    return openbabelJNI.OBAtomBondIter_IsSingle(swigCPtr, this);
  }

  public boolean IsDouble() {
    return openbabelJNI.OBAtomBondIter_IsDouble(swigCPtr, this);
  }

  public boolean IsTriple() {
    return openbabelJNI.OBAtomBondIter_IsTriple(swigCPtr, this);
  }

  public boolean IsKSingle() {
    return openbabelJNI.OBAtomBondIter_IsKSingle(swigCPtr, this);
  }

  public boolean IsKDouble() {
    return openbabelJNI.OBAtomBondIter_IsKDouble(swigCPtr, this);
  }

  public boolean IsKTriple() {
    return openbabelJNI.OBAtomBondIter_IsKTriple(swigCPtr, this);
  }

  public boolean IsClosure() {
    return openbabelJNI.OBAtomBondIter_IsClosure(swigCPtr, this);
  }

  public boolean IsUp() {
    return openbabelJNI.OBAtomBondIter_IsUp(swigCPtr, this);
  }

  public boolean IsDown() {
    return openbabelJNI.OBAtomBondIter_IsDown(swigCPtr, this);
  }

  public boolean IsWedge() {
    return openbabelJNI.OBAtomBondIter_IsWedge(swigCPtr, this);
  }

  public boolean IsHash() {
    return openbabelJNI.OBAtomBondIter_IsHash(swigCPtr, this);
  }

  public boolean IsDoubleBondGeometry() {
    return openbabelJNI.OBAtomBondIter_IsDoubleBondGeometry(swigCPtr, this);
  }

  public boolean Clear() {
    return openbabelJNI.OBAtomBondIter_Clear(swigCPtr, this);
  }

  public OBBase DoTransformations(SWIGTYPE_p_std__mapTstd__string_std__string_t arg0) {
    long cPtr = openbabelJNI.OBAtomBondIter_DoTransformations(swigCPtr, this, SWIGTYPE_p_std__mapTstd__string_std__string_t.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBBase(cPtr, false);
  }

  public String ClassDescription() {
    return openbabelJNI.OBAtomBondIter_ClassDescription(swigCPtr, this);
  }

  public boolean HasData(long type) {
    return openbabelJNI.OBAtomBondIter_HasData__SWIG_2(swigCPtr, this, type);
  }

  public void DeleteData(long type) {
    openbabelJNI.OBAtomBondIter_DeleteData__SWIG_0(swigCPtr, this, type);
  }

  public void DeleteData(OBGenericData arg0) {
    openbabelJNI.OBAtomBondIter_DeleteData__SWIG_1(swigCPtr, this, OBGenericData.getCPtr(arg0), arg0);
  }

  public void DeleteData(vectorData arg0) {
    openbabelJNI.OBAtomBondIter_DeleteData__SWIG_2(swigCPtr, this, vectorData.getCPtr(arg0), arg0);
  }

  public boolean DeleteData(String s) {
    return openbabelJNI.OBAtomBondIter_DeleteData__SWIG_3(swigCPtr, this, s);
  }

  public void SetData(OBGenericData d) {
    openbabelJNI.OBAtomBondIter_SetData(swigCPtr, this, OBGenericData.getCPtr(d), d);
  }

  public long DataSize() {
    return openbabelJNI.OBAtomBondIter_DataSize(swigCPtr, this);
  }

  public OBGenericData GetData(long type) {
    long cPtr = openbabelJNI.OBAtomBondIter_GetData__SWIG_0(swigCPtr, this, type);
    return (cPtr == 0) ? null : new OBGenericData(cPtr, false);
  }

  public vectorData GetData() {
    return new vectorData(openbabelJNI.OBAtomBondIter_GetData__SWIG_3(swigCPtr, this), false);
  }

  public vectorData GetData(DataOrigin source) {
    return new vectorData(openbabelJNI.OBAtomBondIter_GetData__SWIG_4(swigCPtr, this, source.swigValue()), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator BeginData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(openbabelJNI.OBAtomBondIter_BeginData(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator EndData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(openbabelJNI.OBAtomBondIter_EndData(swigCPtr, this), true);
  }

}
