/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBAtom extends OBNodeBase {
  private long swigCPtr;

  protected OBAtom(long cPtr, boolean cMemoryOwn) {
    super(net.sourceforge.openbabelJNI.SWIGOBAtomUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBAtom obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_OBAtom(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OBAtom() {
    this(net.sourceforge.openbabelJNI.new_OBAtom(), true);
  }

  public void Clear() {
    net.sourceforge.openbabelJNI.OBAtom_Clear(swigCPtr, this);
  }

  public void SetIdx(int idx) {
    net.sourceforge.openbabelJNI.OBAtom_SetIdx(swigCPtr, this, idx);
  }

  public void SetHyb(int hyb) {
    net.sourceforge.openbabelJNI.OBAtom_SetHyb(swigCPtr, this, hyb);
  }

  public void SetAtomicNum(int atomicnum) {
    net.sourceforge.openbabelJNI.OBAtom_SetAtomicNum(swigCPtr, this, atomicnum);
  }

  public void SetIsotope(long iso) {
    net.sourceforge.openbabelJNI.OBAtom_SetIsotope(swigCPtr, this, iso);
  }

  public void SetImplicitValence(int val) {
    net.sourceforge.openbabelJNI.OBAtom_SetImplicitValence(swigCPtr, this, val);
  }

  public void IncrementImplicitValence() {
    net.sourceforge.openbabelJNI.OBAtom_IncrementImplicitValence(swigCPtr, this);
  }

  public void DecrementImplicitValence() {
    net.sourceforge.openbabelJNI.OBAtom_DecrementImplicitValence(swigCPtr, this);
  }

  public void SetFormalCharge(int fcharge) {
    net.sourceforge.openbabelJNI.OBAtom_SetFormalCharge(swigCPtr, this, fcharge);
  }

  public void SetSpinMultiplicity(short spin) {
    net.sourceforge.openbabelJNI.OBAtom_SetSpinMultiplicity(swigCPtr, this, spin);
  }

  public void SetType(String type) {
    net.sourceforge.openbabelJNI.OBAtom_SetType__SWIG_0(swigCPtr, this, type);
  }

  public void SetType(SWIGTYPE_p_std__string type) {
    net.sourceforge.openbabelJNI.OBAtom_SetType__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(type));
  }

  public void SetPartialCharge(double pcharge) {
    net.sourceforge.openbabelJNI.OBAtom_SetPartialCharge(swigCPtr, this, pcharge);
  }

  public void SetVector(vector3 v) {
    net.sourceforge.openbabelJNI.OBAtom_SetVector__SWIG_0(swigCPtr, this, vector3.getCPtr(v), v);
  }

  public void SetVector(double x, double y, double z) {
    net.sourceforge.openbabelJNI.OBAtom_SetVector__SWIG_1(swigCPtr, this, x, y, z);
  }

  public void SetCoordPtr(SWIGTYPE_p_p_double c) {
    net.sourceforge.openbabelJNI.OBAtom_SetCoordPtr(swigCPtr, this, SWIGTYPE_p_p_double.getCPtr(c));
  }

  public void SetVector() {
    net.sourceforge.openbabelJNI.OBAtom_SetVector__SWIG_2(swigCPtr, this);
  }

  public void SetResidue(OBResidue res) {
    net.sourceforge.openbabelJNI.OBAtom_SetResidue(swigCPtr, this, OBResidue.getCPtr(res), res);
  }

  public void SetAromatic() {
    net.sourceforge.openbabelJNI.OBAtom_SetAromatic(swigCPtr, this);
  }

  public void UnsetAromatic() {
    net.sourceforge.openbabelJNI.OBAtom_UnsetAromatic(swigCPtr, this);
  }

  public void SetClockwiseStereo() {
    net.sourceforge.openbabelJNI.OBAtom_SetClockwiseStereo(swigCPtr, this);
  }

  public void SetAntiClockwiseStereo() {
    net.sourceforge.openbabelJNI.OBAtom_SetAntiClockwiseStereo(swigCPtr, this);
  }

  public void SetPositiveStereo() {
    net.sourceforge.openbabelJNI.OBAtom_SetPositiveStereo(swigCPtr, this);
  }

  public void SetNegativeStereo() {
    net.sourceforge.openbabelJNI.OBAtom_SetNegativeStereo(swigCPtr, this);
  }

  public void UnsetStereo() {
    net.sourceforge.openbabelJNI.OBAtom_UnsetStereo(swigCPtr, this);
  }

  public void SetInRing() {
    net.sourceforge.openbabelJNI.OBAtom_SetInRing(swigCPtr, this);
  }

  public void SetChiral() {
    net.sourceforge.openbabelJNI.OBAtom_SetChiral(swigCPtr, this);
  }

  public void ClearCoordPtr() {
    net.sourceforge.openbabelJNI.OBAtom_ClearCoordPtr(swigCPtr, this);
  }

  public int GetFormalCharge() {
    return net.sourceforge.openbabelJNI.OBAtom_GetFormalCharge(swigCPtr, this);
  }

  public long GetAtomicNum() {
    return net.sourceforge.openbabelJNI.OBAtom_GetAtomicNum(swigCPtr, this);
  }

  public int GetIsotope() {
    return net.sourceforge.openbabelJNI.OBAtom_GetIsotope(swigCPtr, this);
  }

  public int GetSpinMultiplicity() {
    return net.sourceforge.openbabelJNI.OBAtom_GetSpinMultiplicity(swigCPtr, this);
  }

  public double GetAtomicMass() {
    return net.sourceforge.openbabelJNI.OBAtom_GetAtomicMass(swigCPtr, this);
  }

  public double GetExactMass() {
    return net.sourceforge.openbabelJNI.OBAtom_GetExactMass(swigCPtr, this);
  }

  public long GetIdx() {
    return net.sourceforge.openbabelJNI.OBAtom_GetIdx(swigCPtr, this);
  }

  public long GetCoordinateIdx() {
    return net.sourceforge.openbabelJNI.OBAtom_GetCoordinateIdx(swigCPtr, this);
  }

  public long GetCIdx() {
    return net.sourceforge.openbabelJNI.OBAtom_GetCIdx(swigCPtr, this);
  }

  public long GetValence() {
    return net.sourceforge.openbabelJNI.OBAtom_GetValence(swigCPtr, this);
  }

  public long GetHyb() {
    return net.sourceforge.openbabelJNI.OBAtom_GetHyb(swigCPtr, this);
  }

  public long GetImplicitValence() {
    return net.sourceforge.openbabelJNI.OBAtom_GetImplicitValence(swigCPtr, this);
  }

  public long GetHvyValence() {
    return net.sourceforge.openbabelJNI.OBAtom_GetHvyValence(swigCPtr, this);
  }

  public long GetHeteroValence() {
    return net.sourceforge.openbabelJNI.OBAtom_GetHeteroValence(swigCPtr, this);
  }

  public String GetType() {
    return net.sourceforge.openbabelJNI.OBAtom_GetType(swigCPtr, this);
  }

  public double GetX() {
    return net.sourceforge.openbabelJNI.OBAtom_GetX(swigCPtr, this);
  }

  public double x() {
    return net.sourceforge.openbabelJNI.OBAtom_x(swigCPtr, this);
  }

  public double GetY() {
    return net.sourceforge.openbabelJNI.OBAtom_GetY(swigCPtr, this);
  }

  public double y() {
    return net.sourceforge.openbabelJNI.OBAtom_y(swigCPtr, this);
  }

  public double GetZ() {
    return net.sourceforge.openbabelJNI.OBAtom_GetZ(swigCPtr, this);
  }

  public double z() {
    return net.sourceforge.openbabelJNI.OBAtom_z(swigCPtr, this);
  }

  public SWIGTYPE_p_double GetCoordinate() {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_GetCoordinate(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public vector3 GetVector() {
    return new vector3(net.sourceforge.openbabelJNI.OBAtom_GetVector(swigCPtr, this), false);
  }

  public double GetPartialCharge() {
    return net.sourceforge.openbabelJNI.OBAtom_GetPartialCharge(swigCPtr, this);
  }

  public OBResidue GetResidue() {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_GetResidue(swigCPtr, this);
    return (cPtr == 0) ? null : new OBResidue(cPtr, false);
  }

  public boolean GetNewBondVector(vector3 v, double length) {
    return net.sourceforge.openbabelJNI.OBAtom_GetNewBondVector(swigCPtr, this, vector3.getCPtr(v), v, length);
  }

  public OBBond GetBond(OBAtom arg0) {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_GetBond(swigCPtr, this, OBAtom.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new OBBond(cPtr, false);
  }

  public OBAtom GetNextAtom() {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_GetNextAtom(swigCPtr, this);
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator BeginBonds() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator(net.sourceforge.openbabelJNI.OBAtom_BeginBonds(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator EndBonds() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator(net.sourceforge.openbabelJNI.OBAtom_EndBonds(swigCPtr, this), true);
  }

  public OBBond BeginBond(SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator i) {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_BeginBond(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBBond(cPtr, false);
  }

  public OBBond NextBond(SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator i) {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_NextBond(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBBond(cPtr, false);
  }

  public OBAtom BeginNbrAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator arg0) {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_BeginNbrAtom(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBAtom NextNbrAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator arg0) {
    long cPtr = net.sourceforge.openbabelJNI.OBAtom_NextNbrAtom(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public double GetDistance(int index) {
    return net.sourceforge.openbabelJNI.OBAtom_GetDistance__SWIG_0(swigCPtr, this, index);
  }

  public double GetDistance(OBAtom arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_GetDistance__SWIG_1(swigCPtr, this, OBAtom.getCPtr(arg0), arg0);
  }

  public double GetAngle(int b, int c) {
    return net.sourceforge.openbabelJNI.OBAtom_GetAngle__SWIG_0(swigCPtr, this, b, c);
  }

  public double GetAngle(OBAtom b, OBAtom c) {
    return net.sourceforge.openbabelJNI.OBAtom_GetAngle__SWIG_1(swigCPtr, this, OBAtom.getCPtr(b), b, OBAtom.getCPtr(c), c);
  }

  public void NewResidue() {
    net.sourceforge.openbabelJNI.OBAtom_NewResidue(swigCPtr, this);
  }

  public void DeleteResidue() {
    net.sourceforge.openbabelJNI.OBAtom_DeleteResidue(swigCPtr, this);
  }

  public void AddBond(OBBond bond) {
    net.sourceforge.openbabelJNI.OBAtom_AddBond(swigCPtr, this, OBBond.getCPtr(bond), bond);
  }

  public void InsertBond(SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator i, OBBond bond) {
    net.sourceforge.openbabelJNI.OBAtom_InsertBond(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBEdgeBase_p_t__iterator.getCPtr(i), OBBond.getCPtr(bond), bond);
  }

  public boolean DeleteBond(OBBond arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_DeleteBond(swigCPtr, this, OBBond.getCPtr(arg0), arg0);
  }

  public void ClearBond() {
    net.sourceforge.openbabelJNI.OBAtom_ClearBond(swigCPtr, this);
  }

  public long CountFreeOxygens() {
    return net.sourceforge.openbabelJNI.OBAtom_CountFreeOxygens(swigCPtr, this);
  }

  public long ImplicitHydrogenCount() {
    return net.sourceforge.openbabelJNI.OBAtom_ImplicitHydrogenCount(swigCPtr, this);
  }

  public long ExplicitHydrogenCount(boolean ExcludeIsotopes) {
    return net.sourceforge.openbabelJNI.OBAtom_ExplicitHydrogenCount__SWIG_0(swigCPtr, this, ExcludeIsotopes);
  }

  public long ExplicitHydrogenCount() {
    return net.sourceforge.openbabelJNI.OBAtom_ExplicitHydrogenCount__SWIG_1(swigCPtr, this);
  }

  public long MemberOfRingCount() {
    return net.sourceforge.openbabelJNI.OBAtom_MemberOfRingCount(swigCPtr, this);
  }

  public long MemberOfRingSize() {
    return net.sourceforge.openbabelJNI.OBAtom_MemberOfRingSize(swigCPtr, this);
  }

  public long CountRingBonds() {
    return net.sourceforge.openbabelJNI.OBAtom_CountRingBonds(swigCPtr, this);
  }

  public double SmallestBondAngle() {
    return net.sourceforge.openbabelJNI.OBAtom_SmallestBondAngle(swigCPtr, this);
  }

  public double AverageBondAngle() {
    return net.sourceforge.openbabelJNI.OBAtom_AverageBondAngle(swigCPtr, this);
  }

  public long BOSum() {
    return net.sourceforge.openbabelJNI.OBAtom_BOSum(swigCPtr, this);
  }

  public long KBOSum() {
    return net.sourceforge.openbabelJNI.OBAtom_KBOSum(swigCPtr, this);
  }

  public boolean HtoMethyl() {
    return net.sourceforge.openbabelJNI.OBAtom_HtoMethyl(swigCPtr, this);
  }

  public boolean SetHybAndGeom(int arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_SetHybAndGeom(swigCPtr, this, arg0);
  }

  public void ForceNoH() {
    net.sourceforge.openbabelJNI.OBAtom_ForceNoH(swigCPtr, this);
  }

  public boolean HasNoHForced() {
    return net.sourceforge.openbabelJNI.OBAtom_HasNoHForced(swigCPtr, this);
  }

  public boolean HasResidue() {
    return net.sourceforge.openbabelJNI.OBAtom_HasResidue(swigCPtr, this);
  }

  public boolean IsHydrogen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsHydrogen(swigCPtr, this);
  }

  public boolean IsCarbon() {
    return net.sourceforge.openbabelJNI.OBAtom_IsCarbon(swigCPtr, this);
  }

  public boolean IsNitrogen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsNitrogen(swigCPtr, this);
  }

  public boolean IsOxygen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsOxygen(swigCPtr, this);
  }

  public boolean IsSulfur() {
    return net.sourceforge.openbabelJNI.OBAtom_IsSulfur(swigCPtr, this);
  }

  public boolean IsPhosphorus() {
    return net.sourceforge.openbabelJNI.OBAtom_IsPhosphorus(swigCPtr, this);
  }

  public boolean IsAromatic() {
    return net.sourceforge.openbabelJNI.OBAtom_IsAromatic(swigCPtr, this);
  }

  public boolean IsInRing() {
    return net.sourceforge.openbabelJNI.OBAtom_IsInRing(swigCPtr, this);
  }

  public boolean IsInRingSize(int arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_IsInRingSize(swigCPtr, this, arg0);
  }

  public boolean IsHeteroatom() {
    return net.sourceforge.openbabelJNI.OBAtom_IsHeteroatom(swigCPtr, this);
  }

  public boolean IsNotCorH() {
    return net.sourceforge.openbabelJNI.OBAtom_IsNotCorH(swigCPtr, this);
  }

  public boolean IsConnected(OBAtom arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_IsConnected(swigCPtr, this, OBAtom.getCPtr(arg0), arg0);
  }

  public boolean IsOneThree(OBAtom arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_IsOneThree(swigCPtr, this, OBAtom.getCPtr(arg0), arg0);
  }

  public boolean IsOneFour(OBAtom arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_IsOneFour(swigCPtr, this, OBAtom.getCPtr(arg0), arg0);
  }

  public boolean IsCarboxylOxygen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsCarboxylOxygen(swigCPtr, this);
  }

  public boolean IsPhosphateOxygen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsPhosphateOxygen(swigCPtr, this);
  }

  public boolean IsSulfateOxygen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsSulfateOxygen(swigCPtr, this);
  }

  public boolean IsNitroOxygen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsNitroOxygen(swigCPtr, this);
  }

  public boolean IsAmideNitrogen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsAmideNitrogen(swigCPtr, this);
  }

  public boolean IsPolarHydrogen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsPolarHydrogen(swigCPtr, this);
  }

  public boolean IsNonPolarHydrogen() {
    return net.sourceforge.openbabelJNI.OBAtom_IsNonPolarHydrogen(swigCPtr, this);
  }

  public boolean IsAromaticNOxide() {
    return net.sourceforge.openbabelJNI.OBAtom_IsAromaticNOxide(swigCPtr, this);
  }

  public boolean IsChiral() {
    return net.sourceforge.openbabelJNI.OBAtom_IsChiral(swigCPtr, this);
  }

  public boolean IsAxial() {
    return net.sourceforge.openbabelJNI.OBAtom_IsAxial(swigCPtr, this);
  }

  public boolean IsClockwise() {
    return net.sourceforge.openbabelJNI.OBAtom_IsClockwise(swigCPtr, this);
  }

  public boolean IsAntiClockwise() {
    return net.sourceforge.openbabelJNI.OBAtom_IsAntiClockwise(swigCPtr, this);
  }

  public boolean IsPositiveStereo() {
    return net.sourceforge.openbabelJNI.OBAtom_IsPositiveStereo(swigCPtr, this);
  }

  public boolean IsNegativeStereo() {
    return net.sourceforge.openbabelJNI.OBAtom_IsNegativeStereo(swigCPtr, this);
  }

  public boolean HasChiralitySpecified() {
    return net.sourceforge.openbabelJNI.OBAtom_HasChiralitySpecified(swigCPtr, this);
  }

  public boolean HasChiralVolume() {
    return net.sourceforge.openbabelJNI.OBAtom_HasChiralVolume(swigCPtr, this);
  }

  public boolean IsHbondAcceptor() {
    return net.sourceforge.openbabelJNI.OBAtom_IsHbondAcceptor(swigCPtr, this);
  }

  public boolean IsHbondDonor() {
    return net.sourceforge.openbabelJNI.OBAtom_IsHbondDonor(swigCPtr, this);
  }

  public boolean IsHbondDonorH() {
    return net.sourceforge.openbabelJNI.OBAtom_IsHbondDonorH(swigCPtr, this);
  }

  public boolean HasAlphaBetaUnsat(boolean includePandS) {
    return net.sourceforge.openbabelJNI.OBAtom_HasAlphaBetaUnsat__SWIG_0(swigCPtr, this, includePandS);
  }

  public boolean HasAlphaBetaUnsat() {
    return net.sourceforge.openbabelJNI.OBAtom_HasAlphaBetaUnsat__SWIG_1(swigCPtr, this);
  }

  public boolean HasBondOfOrder(long arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_HasBondOfOrder(swigCPtr, this, arg0);
  }

  public int CountBondsOfOrder(long arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_CountBondsOfOrder(swigCPtr, this, arg0);
  }

  public boolean HasNonSingleBond() {
    return net.sourceforge.openbabelJNI.OBAtom_HasNonSingleBond(swigCPtr, this);
  }

  public boolean HasSingleBond() {
    return net.sourceforge.openbabelJNI.OBAtom_HasSingleBond(swigCPtr, this);
  }

  public boolean HasDoubleBond() {
    return net.sourceforge.openbabelJNI.OBAtom_HasDoubleBond(swigCPtr, this);
  }

  public boolean HasAromaticBond() {
    return net.sourceforge.openbabelJNI.OBAtom_HasAromaticBond(swigCPtr, this);
  }

  public boolean MatchesSMARTS(String arg0) {
    return net.sourceforge.openbabelJNI.OBAtom_MatchesSMARTS(swigCPtr, this, arg0);
  }

}
