/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBChiralData extends OBGenericData {
  private long swigCPtr;

  protected OBChiralData(long cPtr, boolean cMemoryOwn) {
    super(net.sourceforge.openbabelJNI.SWIGOBChiralDataUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBChiralData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_OBChiralData(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public SWIGTYPE_p_std__vectorTunsigned_int_t GetAtom4Refs(atomreftype t) {
    return new SWIGTYPE_p_std__vectorTunsigned_int_t(net.sourceforge.openbabelJNI.OBChiralData_GetAtom4Refs(swigCPtr, t.swigValue()), true);
  }

  public long GetAtomRef(int a, atomreftype t) {
    return net.sourceforge.openbabelJNI.OBChiralData_GetAtomRef(swigCPtr, a, t.swigValue());
  }

  public OBChiralData() {
    this(net.sourceforge.openbabelJNI.new_OBChiralData__SWIG_0(), true);
  }

  public OBChiralData(OBChiralData src) {
    this(net.sourceforge.openbabelJNI.new_OBChiralData__SWIG_1(OBChiralData.getCPtr(src)), true);
  }

  public OBGenericData Clone(OBBase arg0) {
    long cPtr = net.sourceforge.openbabelJNI.OBChiralData_Clone(swigCPtr, OBBase.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBGenericData(cPtr, false);
  }

  public void Clear() {
    net.sourceforge.openbabelJNI.OBChiralData_Clear(swigCPtr);
  }

  public boolean SetAtom4Refs(SWIGTYPE_p_std__vectorTunsigned_int_t atom4refs, atomreftype t) {
    return net.sourceforge.openbabelJNI.OBChiralData_SetAtom4Refs(swigCPtr, SWIGTYPE_p_std__vectorTunsigned_int_t.getCPtr(atom4refs), t.swigValue());
  }

  public int AddAtomRef(long atomref, atomreftype t) {
    return net.sourceforge.openbabelJNI.OBChiralData_AddAtomRef(swigCPtr, atomref, t.swigValue());
  }

  public long GetSize(atomreftype t) {
    return net.sourceforge.openbabelJNI.OBChiralData_GetSize(swigCPtr, t.swigValue());
  }

}
