/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBGlobalDataBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBGlobalDataBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBGlobalDataBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_OBGlobalDataBase(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBGlobalDataBase() {
    this(net.sourceforge.openbabelJNI.new_OBGlobalDataBase(), true);
  }

  public void Init() {
    net.sourceforge.openbabelJNI.OBGlobalDataBase_Init(swigCPtr);
  }

  public long GetSize() {
    return net.sourceforge.openbabelJNI.OBGlobalDataBase_GetSize(swigCPtr);
  }

  public void SetReadDirectory(String dir) {
    net.sourceforge.openbabelJNI.OBGlobalDataBase_SetReadDirectory(swigCPtr, dir);
  }

  public void SetEnvironmentVariable(String var) {
    net.sourceforge.openbabelJNI.OBGlobalDataBase_SetEnvironmentVariable(swigCPtr, var);
  }

  public void ParseLine(String arg0) {
    net.sourceforge.openbabelJNI.OBGlobalDataBase_ParseLine(swigCPtr, arg0);
  }

}
