/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBMolTorsionIter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBMolTorsionIter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBMolTorsionIter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBMolTorsionIter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBMolTorsionIter() {
    this(openbabelJNI.new_OBMolTorsionIter__SWIG_0(), true);
  }

  public OBMolTorsionIter(OBMol mol) {
    this(openbabelJNI.new_OBMolTorsionIter__SWIG_1(OBMol.getCPtr(mol), mol), true);
  }

  public OBMolTorsionIter(OBMolTorsionIter ai) {
    this(openbabelJNI.new_OBMolTorsionIter__SWIG_3(OBMolTorsionIter.getCPtr(ai), ai), true);
  }

  public SWIGTYPE_p_std__vectorTunsigned_int_t __ref__() {
    return new SWIGTYPE_p_std__vectorTunsigned_int_t(openbabelJNI.OBMolTorsionIter___ref__(swigCPtr, this), true);
  }

}
