/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBPSA extends OBGroupContrib {
  private long swigCPtr;

  protected OBPSA(long cPtr, boolean cMemoryOwn) {
    super(openbabelJNI.SWIGOBPSAUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBPSA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBPSA(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OBPSA() {
    this(openbabelJNI.new_OBPSA(), true);
  }

  public double Predict(OBMol mol) {
    return openbabelJNI.OBPSA_Predict(swigCPtr, this, OBMol.getCPtr(mol), mol);
  }

}
