/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBRandom {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBRandom(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBRandom obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_OBRandom(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBRandom(boolean useSys) {
    this(net.sourceforge.openbabelJNI.new_OBRandom__SWIG_0(useSys), true);
  }

  public OBRandom() {
    this(net.sourceforge.openbabelJNI.new_OBRandom__SWIG_1(), true);
  }

  public void Seed(int seed) {
    net.sourceforge.openbabelJNI.OBRandom_Seed(swigCPtr, seed);
  }

  public void TimeSeed() {
    net.sourceforge.openbabelJNI.OBRandom_TimeSeed(swigCPtr);
  }

  public int NextInt() {
    return net.sourceforge.openbabelJNI.OBRandom_NextInt(swigCPtr);
  }

  public double NextFloat() {
    return net.sourceforge.openbabelJNI.OBRandom_NextFloat(swigCPtr);
  }

}
