/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBResidueIter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBResidueIter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBResidueIter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBResidueIter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBResidueIter() {
    this(openbabelJNI.new_OBResidueIter__SWIG_0(), true);
  }

  public OBResidueIter(OBMol mol) {
    this(openbabelJNI.new_OBResidueIter__SWIG_1(OBMol.getCPtr(mol), mol), true);
  }

  public OBResidueIter(OBResidueIter ri) {
    this(openbabelJNI.new_OBResidueIter__SWIG_2(OBResidueIter.getCPtr(ri), ri), true);
  }

  public OBResidue __deref__() {
    long cPtr = openbabelJNI.OBResidueIter___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new OBResidue(cPtr, false);
  }

  public OBResidue __ref__() {
    return new OBResidue(openbabelJNI.OBResidueIter___ref__(swigCPtr, this), false);
  }

  public void AddAtom(OBAtom atom) {
    openbabelJNI.OBResidueIter_AddAtom(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public void InsertAtom(OBAtom atom) {
    openbabelJNI.OBResidueIter_InsertAtom(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public void RemoveAtom(OBAtom atom) {
    openbabelJNI.OBResidueIter_RemoveAtom(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public boolean Clear() {
    return openbabelJNI.OBResidueIter_Clear(swigCPtr, this);
  }

  public void SetName(String resname) {
    openbabelJNI.OBResidueIter_SetName(swigCPtr, this, resname);
  }

  public void SetNum(long resnum) {
    openbabelJNI.OBResidueIter_SetNum(swigCPtr, this, resnum);
  }

  public void SetChain(char chain) {
    openbabelJNI.OBResidueIter_SetChain(swigCPtr, this, chain);
  }

  public void SetChainNum(long chainnum) {
    openbabelJNI.OBResidueIter_SetChainNum(swigCPtr, this, chainnum);
  }

  public void SetIdx(long idx) {
    openbabelJNI.OBResidueIter_SetIdx(swigCPtr, this, idx);
  }

  public void SetAtomID(OBAtom atom, String id) {
    openbabelJNI.OBResidueIter_SetAtomID(swigCPtr, this, OBAtom.getCPtr(atom), atom, id);
  }

  public void SetHetAtom(OBAtom atom, boolean hetatm) {
    openbabelJNI.OBResidueIter_SetHetAtom(swigCPtr, this, OBAtom.getCPtr(atom), atom, hetatm);
  }

  public void SetSerialNum(OBAtom atom, long sernum) {
    openbabelJNI.OBResidueIter_SetSerialNum(swigCPtr, this, OBAtom.getCPtr(atom), atom, sernum);
  }

  public String GetName() {
    return openbabelJNI.OBResidueIter_GetName(swigCPtr, this);
  }

  public long GetNum() {
    return openbabelJNI.OBResidueIter_GetNum(swigCPtr, this);
  }

  public long GetNumAtoms() {
    return openbabelJNI.OBResidueIter_GetNumAtoms(swigCPtr, this);
  }

  public char GetChain() {
    return openbabelJNI.OBResidueIter_GetChain(swigCPtr, this);
  }

  public long GetChainNum() {
    return openbabelJNI.OBResidueIter_GetChainNum(swigCPtr, this);
  }

  public long GetIdx() {
    return openbabelJNI.OBResidueIter_GetIdx(swigCPtr, this);
  }

  public long GetResKey() {
    return openbabelJNI.OBResidueIter_GetResKey(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t GetAtoms() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t(openbabelJNI.OBResidueIter_GetAtoms(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t GetBonds(boolean exterior) {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t(openbabelJNI.OBResidueIter_GetBonds__SWIG_0(swigCPtr, this, exterior), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t GetBonds() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t(openbabelJNI.OBResidueIter_GetBonds__SWIG_1(swigCPtr, this), true);
  }

  public String GetAtomID(OBAtom atom) {
    return openbabelJNI.OBResidueIter_GetAtomID(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public long GetSerialNum(OBAtom atom) {
    return openbabelJNI.OBResidueIter_GetSerialNum(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public boolean GetAminoAcidProperty(int arg0) {
    return openbabelJNI.OBResidueIter_GetAminoAcidProperty(swigCPtr, this, arg0);
  }

  public boolean GetAtomProperty(OBAtom a, int arg1) {
    return openbabelJNI.OBResidueIter_GetAtomProperty(swigCPtr, this, OBAtom.getCPtr(a), a, arg1);
  }

  public boolean GetResidueProperty(int arg0) {
    return openbabelJNI.OBResidueIter_GetResidueProperty(swigCPtr, this, arg0);
  }

  public boolean IsHetAtom(OBAtom atom) {
    return openbabelJNI.OBResidueIter_IsHetAtom(swigCPtr, this, OBAtom.getCPtr(atom), atom);
  }

  public boolean IsResidueType(int arg0) {
    return openbabelJNI.OBResidueIter_IsResidueType(swigCPtr, this, arg0);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator BeginAtoms() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator(openbabelJNI.OBResidueIter_BeginAtoms(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator EndAtoms() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator(openbabelJNI.OBResidueIter_EndAtoms(swigCPtr, this), true);
  }

  public OBAtom BeginAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator i) {
    long cPtr = openbabelJNI.OBResidueIter_BeginAtom(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBAtom NextAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator i) {
    long cPtr = openbabelJNI.OBResidueIter_NextAtom(swigCPtr, this, SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBBase DoTransformations(SWIGTYPE_p_std__mapTstd__string_std__string_t arg0) {
    long cPtr = openbabelJNI.OBResidueIter_DoTransformations(swigCPtr, this, SWIGTYPE_p_std__mapTstd__string_std__string_t.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBBase(cPtr, false);
  }

  public String ClassDescription() {
    return openbabelJNI.OBResidueIter_ClassDescription(swigCPtr, this);
  }

  public boolean HasData(long type) {
    return openbabelJNI.OBResidueIter_HasData__SWIG_2(swigCPtr, this, type);
  }

  public void DeleteData(long type) {
    openbabelJNI.OBResidueIter_DeleteData__SWIG_0(swigCPtr, this, type);
  }

  public void DeleteData(OBGenericData arg0) {
    openbabelJNI.OBResidueIter_DeleteData__SWIG_1(swigCPtr, this, OBGenericData.getCPtr(arg0), arg0);
  }

  public void DeleteData(vectorData arg0) {
    openbabelJNI.OBResidueIter_DeleteData__SWIG_2(swigCPtr, this, vectorData.getCPtr(arg0), arg0);
  }

  public boolean DeleteData(String s) {
    return openbabelJNI.OBResidueIter_DeleteData__SWIG_3(swigCPtr, this, s);
  }

  public void SetData(OBGenericData d) {
    openbabelJNI.OBResidueIter_SetData(swigCPtr, this, OBGenericData.getCPtr(d), d);
  }

  public long DataSize() {
    return openbabelJNI.OBResidueIter_DataSize(swigCPtr, this);
  }

  public OBGenericData GetData(long type) {
    long cPtr = openbabelJNI.OBResidueIter_GetData__SWIG_0(swigCPtr, this, type);
    return (cPtr == 0) ? null : new OBGenericData(cPtr, false);
  }

  public vectorData GetData() {
    return new vectorData(openbabelJNI.OBResidueIter_GetData__SWIG_3(swigCPtr, this), false);
  }

  public vectorData GetData(DataOrigin source) {
    return new vectorData(openbabelJNI.OBResidueIter_GetData__SWIG_4(swigCPtr, this, source.swigValue()), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator BeginData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(openbabelJNI.OBResidueIter_BeginData(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator EndData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(openbabelJNI.OBResidueIter_EndData(swigCPtr, this), true);
  }

}
