/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBResidueIter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBResidueIter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBResidueIter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_OBResidueIter(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBResidueIter() {
    this(net.sourceforge.openbabelJNI.new_OBResidueIter__SWIG_0(), true);
  }

  public OBResidueIter(OBMol mol) {
    this(net.sourceforge.openbabelJNI.new_OBResidueIter__SWIG_1(OBMol.getCPtr(mol)), true);
  }

  public OBResidueIter(OBResidueIter ri) {
    this(net.sourceforge.openbabelJNI.new_OBResidueIter__SWIG_3(OBResidueIter.getCPtr(ri)), true);
  }

  public boolean good() {
    return net.sourceforge.openbabelJNI.OBResidueIter_good(swigCPtr);
  }

  public OBResidueIter inc(int arg0) {
    return new OBResidueIter(net.sourceforge.openbabelJNI.OBResidueIter_inc(swigCPtr, arg0), true);
  }

  public OBResidue __deref__() {
    long cPtr = net.sourceforge.openbabelJNI.OBResidueIter___deref__(swigCPtr);
    return (cPtr == 0) ? null : new OBResidue(cPtr, false);
  }

  public OBResidue __ref__() {
    return new OBResidue(net.sourceforge.openbabelJNI.OBResidueIter___ref__(swigCPtr), false);
  }

  public void AddAtom(OBAtom atom) {
    net.sourceforge.openbabelJNI.OBResidueIter_AddAtom(swigCPtr, OBAtom.getCPtr(atom));
  }

  public void InsertAtom(OBAtom atom) {
    net.sourceforge.openbabelJNI.OBResidueIter_InsertAtom(swigCPtr, OBAtom.getCPtr(atom));
  }

  public void RemoveAtom(OBAtom atom) {
    net.sourceforge.openbabelJNI.OBResidueIter_RemoveAtom(swigCPtr, OBAtom.getCPtr(atom));
  }

  public void Clear() {
    net.sourceforge.openbabelJNI.OBResidueIter_Clear(swigCPtr);
  }

  public void SetName(String resname) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetName(swigCPtr, resname);
  }

  public void SetNum(long resnum) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetNum(swigCPtr, resnum);
  }

  public void SetChain(char chain) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetChain(swigCPtr, chain);
  }

  public void SetChainNum(long chainnum) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetChainNum(swigCPtr, chainnum);
  }

  public void SetIdx(long idx) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetIdx(swigCPtr, idx);
  }

  public void SetAtomID(OBAtom atom, String id) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetAtomID(swigCPtr, OBAtom.getCPtr(atom), id);
  }

  public void SetHetAtom(OBAtom atom, boolean hetatm) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetHetAtom(swigCPtr, OBAtom.getCPtr(atom), hetatm);
  }

  public void SetSerialNum(OBAtom atom, long sernum) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetSerialNum(swigCPtr, OBAtom.getCPtr(atom), sernum);
  }

  public String GetName() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetName(swigCPtr);
  }

  public long GetNum() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetNum(swigCPtr);
  }

  public long GetNumAtoms() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetNumAtoms(swigCPtr);
  }

  public char GetChain() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetChain(swigCPtr);
  }

  public long GetChainNum() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetChainNum(swigCPtr);
  }

  public long GetIdx() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetIdx(swigCPtr);
  }

  public long GetResKey() {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetResKey(swigCPtr);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t GetAtoms() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t(net.sourceforge.openbabelJNI.OBResidueIter_GetAtoms(swigCPtr), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t GetBonds(boolean exterior) {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t(net.sourceforge.openbabelJNI.OBResidueIter_GetBonds__SWIG_0(swigCPtr, exterior), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t GetBonds() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBBond_p_t(net.sourceforge.openbabelJNI.OBResidueIter_GetBonds__SWIG_1(swigCPtr), true);
  }

  public String GetAtomID(OBAtom atom) {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetAtomID(swigCPtr, OBAtom.getCPtr(atom));
  }

  public long GetSerialNum(OBAtom atom) {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetSerialNum(swigCPtr, OBAtom.getCPtr(atom));
  }

  public boolean GetAminoAcidProperty(int arg0) {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetAminoAcidProperty(swigCPtr, arg0);
  }

  public boolean GetAtomProperty(OBAtom arg0, int arg1) {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetAtomProperty(swigCPtr, OBAtom.getCPtr(arg0), arg1);
  }

  public boolean GetResidueProperty(int arg0) {
    return net.sourceforge.openbabelJNI.OBResidueIter_GetResidueProperty(swigCPtr, arg0);
  }

  public boolean IsHetAtom(OBAtom atom) {
    return net.sourceforge.openbabelJNI.OBResidueIter_IsHetAtom(swigCPtr, OBAtom.getCPtr(atom));
  }

  public boolean IsResidueType(int arg0) {
    return net.sourceforge.openbabelJNI.OBResidueIter_IsResidueType(swigCPtr, arg0);
  }

  public OBAtom BeginAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator i) {
    long cPtr = net.sourceforge.openbabelJNI.OBResidueIter_BeginAtom(swigCPtr, SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBAtom NextAtom(SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator i) {
    long cPtr = net.sourceforge.openbabelJNI.OBResidueIter_NextAtom(swigCPtr, SWIGTYPE_p_std__vectorTOpenBabel__OBAtom_p_t__iterator.getCPtr(i));
    return (cPtr == 0) ? null : new OBAtom(cPtr, false);
  }

  public OBBase DoTransformations(SWIGTYPE_p_std__mapTstd__string_std__string_t arg0) {
    long cPtr = net.sourceforge.openbabelJNI.OBResidueIter_DoTransformations(swigCPtr, SWIGTYPE_p_std__mapTstd__string_std__string_t.getCPtr(arg0));
    return (cPtr == 0) ? null : new OBBase(cPtr, false);
  }

  public String ClassDescription() {
    return net.sourceforge.openbabelJNI.OBResidueIter_ClassDescription(swigCPtr);
  }

  public boolean HasData(long type) {
    return net.sourceforge.openbabelJNI.OBResidueIter_HasData__SWIG_2(swigCPtr, type);
  }

  public void DeleteData(long type) {
    net.sourceforge.openbabelJNI.OBResidueIter_DeleteData__SWIG_0(swigCPtr, type);
  }

  public void DeleteData(OBGenericData arg0) {
    net.sourceforge.openbabelJNI.OBResidueIter_DeleteData__SWIG_1(swigCPtr, OBGenericData.getCPtr(arg0));
  }

  public void DeleteData(vectorData arg0) {
    net.sourceforge.openbabelJNI.OBResidueIter_DeleteData__SWIG_2(swigCPtr, vectorData.getCPtr(arg0));
  }

  public void SetData(OBGenericData d) {
    net.sourceforge.openbabelJNI.OBResidueIter_SetData(swigCPtr, OBGenericData.getCPtr(d));
  }

  public long DataSize() {
    return net.sourceforge.openbabelJNI.OBResidueIter_DataSize(swigCPtr);
  }

  public OBGenericData GetData(long type) {
    long cPtr = net.sourceforge.openbabelJNI.OBResidueIter_GetData__SWIG_0(swigCPtr, type);
    return (cPtr == 0) ? null : new OBGenericData(cPtr, false);
  }

  public vectorData GetData() {
    return new vectorData(net.sourceforge.openbabelJNI.OBResidueIter_GetData__SWIG_3(swigCPtr), false);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator BeginData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(net.sourceforge.openbabelJNI.OBResidueIter_BeginData(swigCPtr), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator EndData() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__OBGenericData_p_t__iterator(net.sourceforge.openbabelJNI.OBResidueIter_EndData(swigCPtr), true);
  }

}
