/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBTorsion {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OBTorsion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBTorsion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBTorsion(swigCPtr);
    }
    swigCPtr = 0;
  }

  public OBTorsion(OBTorsion arg0) {
    this(openbabelJNI.new_OBTorsion__SWIG_2(OBTorsion.getCPtr(arg0), arg0), true);
  }

  public void Clear() {
    openbabelJNI.OBTorsion_Clear(swigCPtr, this);
  }

  public boolean Empty() {
    return openbabelJNI.OBTorsion_Empty(swigCPtr, this);
  }

  public boolean AddTorsion(OBAtom a, OBAtom b, OBAtom c, OBAtom d) {
    return openbabelJNI.OBTorsion_AddTorsion__SWIG_0(swigCPtr, this, OBAtom.getCPtr(a), a, OBAtom.getCPtr(b), b, OBAtom.getCPtr(c), c, OBAtom.getCPtr(d), d);
  }

  public boolean AddTorsion(SWIGTYPE_p_OpenBabel__quadTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_OpenBabel__OBAtom_p_OpenBabel__OBAtom_p_t atoms) {
    return openbabelJNI.OBTorsion_AddTorsion__SWIG_1(swigCPtr, this, SWIGTYPE_p_OpenBabel__quadTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_OpenBabel__OBAtom_p_OpenBabel__OBAtom_p_t.getCPtr(atoms));
  }

  public boolean SetAngle(double radians, long index) {
    return openbabelJNI.OBTorsion_SetAngle__SWIG_0(swigCPtr, this, radians, index);
  }

  public boolean SetAngle(double radians) {
    return openbabelJNI.OBTorsion_SetAngle__SWIG_1(swigCPtr, this, radians);
  }

  public boolean SetData(OBBond arg0) {
    return openbabelJNI.OBTorsion_SetData(swigCPtr, this, OBBond.getCPtr(arg0), arg0);
  }

  public boolean GetAngle(SWIGTYPE_p_double radians, long index) {
    return openbabelJNI.OBTorsion_GetAngle__SWIG_0(swigCPtr, this, SWIGTYPE_p_double.getCPtr(radians), index);
  }

  public boolean GetAngle(SWIGTYPE_p_double radians) {
    return openbabelJNI.OBTorsion_GetAngle__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(radians));
  }

  public long GetBondIdx() {
    return openbabelJNI.OBTorsion_GetBondIdx(swigCPtr, this);
  }

  public long GetSize() {
    return openbabelJNI.OBTorsion_GetSize(swigCPtr, this);
  }

  public SWIGTYPE_p_std__pairTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_t GetBC() {
    return new SWIGTYPE_p_std__pairTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_t(openbabelJNI.OBTorsion_GetBC(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorTOpenBabel__tripleTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_double_t_t GetADs() {
    return new SWIGTYPE_p_std__vectorTOpenBabel__tripleTOpenBabel__OBAtom_p_OpenBabel__OBAtom_p_double_t_t(openbabelJNI.OBTorsion_GetADs(swigCPtr, this), true);
  }

  public boolean IsProtonRotor() {
    return openbabelJNI.OBTorsion_IsProtonRotor(swigCPtr, this);
  }

}
