/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OBVirtualBond extends OBGenericData {
  private long swigCPtr;

  protected OBVirtualBond(long cPtr, boolean cMemoryOwn) {
    super(openbabelJNI.SWIGOBVirtualBondUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OBVirtualBond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_OBVirtualBond(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public OBVirtualBond() {
    this(openbabelJNI.new_OBVirtualBond__SWIG_0(), true);
  }

  public OBGenericData Clone(OBBase arg0) {
    long cPtr = openbabelJNI.OBVirtualBond_Clone(swigCPtr, this, OBBase.getCPtr(arg0), arg0);
    return (cPtr == 0) ? null : new OBGenericData(cPtr, false);
  }

  public OBVirtualBond(int arg0, int arg1, int arg2, int stereo) {
    this(openbabelJNI.new_OBVirtualBond__SWIG_1(arg0, arg1, arg2, stereo), true);
  }

  public OBVirtualBond(int arg0, int arg1, int arg2) {
    this(openbabelJNI.new_OBVirtualBond__SWIG_2(arg0, arg1, arg2), true);
  }

  public int GetBgn() {
    return openbabelJNI.OBVirtualBond_GetBgn(swigCPtr, this);
  }

  public int GetEnd() {
    return openbabelJNI.OBVirtualBond_GetEnd(swigCPtr, this);
  }

  public int GetOrder() {
    return openbabelJNI.OBVirtualBond_GetOrder(swigCPtr, this);
  }

  public int GetStereo() {
    return openbabelJNI.OBVirtualBond_GetStereo(swigCPtr, this);
  }

}
