/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorBond {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorBond(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorBond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_vectorBond(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vectorBond() {
    this(openbabelJNI.new_vectorBond__SWIG_0(), true);
  }

  public vectorBond(long n) {
    this(openbabelJNI.new_vectorBond__SWIG_1(n), true);
  }

  public long size() {
    return openbabelJNI.vectorBond_size(swigCPtr, this);
  }

  public long capacity() {
    return openbabelJNI.vectorBond_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    openbabelJNI.vectorBond_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return openbabelJNI.vectorBond_isEmpty(swigCPtr, this);
  }

  public void clear() {
    openbabelJNI.vectorBond_clear(swigCPtr, this);
  }

  public void add(OBBond x) {
    openbabelJNI.vectorBond_add(swigCPtr, this, OBBond.getCPtr(x), x);
  }

  public OBBond get(int i) {
    return new OBBond(openbabelJNI.vectorBond_get(swigCPtr, this, i), false);
  }

  public void set(int i, OBBond x) {
    openbabelJNI.vectorBond_set(swigCPtr, this, i, OBBond.getCPtr(x), x);
  }

}
