/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorMol {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorMol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorMol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_vectorMol(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vectorMol() {
    this(net.sourceforge.openbabelJNI.new_vectorMol__SWIG_0(), true);
  }

  public vectorMol(long n) {
    this(net.sourceforge.openbabelJNI.new_vectorMol__SWIG_1(n), true);
  }

  public long size() {
    return net.sourceforge.openbabelJNI.vectorMol_size(swigCPtr);
  }

  public long capacity() {
    return net.sourceforge.openbabelJNI.vectorMol_capacity(swigCPtr);
  }

  public void reserve(long n) {
    net.sourceforge.openbabelJNI.vectorMol_reserve(swigCPtr, n);
  }

  public boolean isEmpty() {
    return net.sourceforge.openbabelJNI.vectorMol_isEmpty(swigCPtr);
  }

  public void clear() {
    net.sourceforge.openbabelJNI.vectorMol_clear(swigCPtr);
  }

  public void add(OBMol x) {
    net.sourceforge.openbabelJNI.vectorMol_add(swigCPtr, OBMol.getCPtr(x));
  }

  public OBMol get(int i) {
    return new OBMol(net.sourceforge.openbabelJNI.vectorMol_get(swigCPtr, i), false);
  }

  public void set(int i, OBMol x) {
    net.sourceforge.openbabelJNI.vectorMol_set(swigCPtr, i, OBMol.getCPtr(x));
  }

}
