/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorBond {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorBond(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorBond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_vectorBond(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vectorBond() {
    this(net.sourceforge.openbabelJNI.new_vectorBond__SWIG_0(), true);
  }

  public vectorBond(long n) {
    this(net.sourceforge.openbabelJNI.new_vectorBond__SWIG_1(n), true);
  }

  public long size() {
    return net.sourceforge.openbabelJNI.vectorBond_size(swigCPtr);
  }

  public long capacity() {
    return net.sourceforge.openbabelJNI.vectorBond_capacity(swigCPtr);
  }

  public void reserve(long n) {
    net.sourceforge.openbabelJNI.vectorBond_reserve(swigCPtr, n);
  }

  public boolean isEmpty() {
    return net.sourceforge.openbabelJNI.vectorBond_isEmpty(swigCPtr);
  }

  public void clear() {
    net.sourceforge.openbabelJNI.vectorBond_clear(swigCPtr);
  }

  public void add(OBBond x) {
    net.sourceforge.openbabelJNI.vectorBond_add(swigCPtr, OBBond.getCPtr(x));
  }

  public OBBond get(int i) {
    return new OBBond(net.sourceforge.openbabelJNI.vectorBond_get(swigCPtr, i), false);
  }

  public void set(int i, OBBond x) {
    net.sourceforge.openbabelJNI.vectorBond_set(swigCPtr, i, OBBond.getCPtr(x));
  }

}
