/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorpRing {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorpRing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorpRing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_vectorpRing(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vectorpRing() {
    this(openbabelJNI.new_vectorpRing__SWIG_0(), true);
  }

  public vectorpRing(long n) {
    this(openbabelJNI.new_vectorpRing__SWIG_1(n), true);
  }

  public long size() {
    return openbabelJNI.vectorpRing_size(swigCPtr, this);
  }

  public long capacity() {
    return openbabelJNI.vectorpRing_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    openbabelJNI.vectorpRing_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return openbabelJNI.vectorpRing_isEmpty(swigCPtr, this);
  }

  public void clear() {
    openbabelJNI.vectorpRing_clear(swigCPtr, this);
  }

  public void add(OBRing x) {
    openbabelJNI.vectorpRing_add(swigCPtr, this, OBRing.getCPtr(x));
  }

  public OBRing get(int i) {
    long cPtr = openbabelJNI.vectorpRing_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new OBRing(cPtr, false);
  }

  public void set(int i, OBRing x) {
    openbabelJNI.vectorpRing_set(swigCPtr, this, i, OBRing.getCPtr(x));
  }

}
