/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vectorString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vectorString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      openbabelJNI.delete_vectorString(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vectorString() {
    this(openbabelJNI.new_vectorString__SWIG_0(), true);
  }

  public vectorString(long n) {
    this(openbabelJNI.new_vectorString__SWIG_1(n), true);
  }

  public long size() {
    return openbabelJNI.vectorString_size(swigCPtr, this);
  }

  public long capacity() {
    return openbabelJNI.vectorString_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    openbabelJNI.vectorString_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return openbabelJNI.vectorString_isEmpty(swigCPtr, this);
  }

  public void clear() {
    openbabelJNI.vectorString_clear(swigCPtr, this);
  }

  public void add(String x) {
    openbabelJNI.vectorString_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return openbabelJNI.vectorString_get(swigCPtr, this, i);
  }

  public void set(int i, String x) {
    openbabelJNI.vectorString_set(swigCPtr, this, i, x);
  }

}
