/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vVector3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vVector3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vVector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_vVector3(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vVector3() {
    this(net.sourceforge.openbabelJNI.new_vVector3__SWIG_0(), true);
  }

  public vVector3(long n) {
    this(net.sourceforge.openbabelJNI.new_vVector3__SWIG_1(n), true);
  }

  public long size() {
    return net.sourceforge.openbabelJNI.vVector3_size(swigCPtr);
  }

  public long capacity() {
    return net.sourceforge.openbabelJNI.vVector3_capacity(swigCPtr);
  }

  public void reserve(long n) {
    net.sourceforge.openbabelJNI.vVector3_reserve(swigCPtr, n);
  }

  public boolean isEmpty() {
    return net.sourceforge.openbabelJNI.vVector3_isEmpty(swigCPtr);
  }

  public void clear() {
    net.sourceforge.openbabelJNI.vVector3_clear(swigCPtr);
  }

  public void add(vector3 x) {
    net.sourceforge.openbabelJNI.vVector3_add(swigCPtr, vector3.getCPtr(x));
  }

  public vector3 get(int i) {
    return new vector3(net.sourceforge.openbabelJNI.vVector3_get(swigCPtr, i), false);
  }

  public void set(int i, vector3 x) {
    net.sourceforge.openbabelJNI.vVector3_set(swigCPtr, i, vector3.getCPtr(x));
  }

}
