/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vvInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vvInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vvInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      net.sourceforge.openbabelJNI.delete_vvInt(swigCPtr);
    }
    swigCPtr = 0;
  }

  public vvInt() {
    this(net.sourceforge.openbabelJNI.new_vvInt__SWIG_0(), true);
  }

  public vvInt(long n) {
    this(net.sourceforge.openbabelJNI.new_vvInt__SWIG_1(n), true);
  }

  public long size() {
    return net.sourceforge.openbabelJNI.vvInt_size(swigCPtr);
  }

  public long capacity() {
    return net.sourceforge.openbabelJNI.vvInt_capacity(swigCPtr);
  }

  public void reserve(long n) {
    net.sourceforge.openbabelJNI.vvInt_reserve(swigCPtr, n);
  }

  public boolean isEmpty() {
    return net.sourceforge.openbabelJNI.vvInt_isEmpty(swigCPtr);
  }

  public void clear() {
    net.sourceforge.openbabelJNI.vvInt_clear(swigCPtr);
  }

  public void add(vectorInt x) {
    net.sourceforge.openbabelJNI.vvInt_add(swigCPtr, vectorInt.getCPtr(x));
  }

  public vectorInt get(int i) {
    return new vectorInt(net.sourceforge.openbabelJNI.vvInt_get(swigCPtr, i), false);
  }

  public void set(int i, vectorInt x) {
    net.sourceforge.openbabelJNI.vvInt_set(swigCPtr, i, vectorInt.getCPtr(x));
  }

}
