name: misspell-fixer

# on: [push]
jobs:
  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: misspell-fixer check for code and comments
      uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rsvn include/openbabel src tools'
    - uses: peter-evans/create-pull-request@v8.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
